### ISSUE TITLE
Add support to stop and start child clusters at given interval

### ISSUE THREAD

**Issue by rasheedamir** [openshift/hive#1033]
From cost savings perspective; it will be great to have a feature to turn off non-prod child cluster over night after the work hours and over weekends.

**Comment by dgoodwin** [comment]
OpenShift recently gained support for bypassing the cert problems that surface when you do this and it is not possible to pause a cluster that has not done its initial 30 day cert renewal, you just have to manually approve CSRs on startup again, at which point you're good for 30 days.

@csrwng is working on a design and implementation for supporting this in hive.

**Comment by rasheedamir** [comment]
The support is available now for AWS, GCP and Azure
