### ISSUE TITLE
Can the `hiveImage` and `installerImage` be removed or optional?

### ISSUE THREAD

**Issue by jhernand** [openshift/hive#104]
Currently in order to create a cluster deployment the user of the API has to explicitly specify the `hiveImage` and the `installerImage` parameters. This is error prone, as it is easy to make mistakes and easy to use images that aren't in sync with the rest of Hive. Can this be removed or made optional? If optional then Hive should have information/configuration enough to decide what are the right images to use.

**Comment by dgoodwin** [comment]
They are optional today, but the default is the CI registry, which does not match what you requested for weekly content drops. 

I don't know if they will permanently be in the Hive API, or take a different form, I need to get a better look at how you will install specific builds of OpenShift 4.0 before we know the final form. 

We could perhaps move the images to use to a Hive-wide config map, but we'd still need a solution for "what version do you want to install". 

So optional already, probably will change in future, but for now they are the only means for you to pin the version of Hive/Installer to use weekly.
