### ISSUE TITLE
cluster provisioning doesn't finish

### ISSUE THREAD

**Issue by oourfali** [openshift/hive#110]
I've provisioned a cluster using api.openshift.com.

As a result I see the instances were created in AWS, however the bootstrap node is still running.
The end of the output of "journalctl --unit=bootkube.service" on the bootstrap node is:

Nov 26 14:32:48 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-apiserver/openshift-kube-apiserver        DoesNotExist
Nov 26 14:32:53 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-controller-manager/openshift-kube-controller-manager-ip-10-0-43-201.ec2.internal        Pending
Nov 26 14:32:53 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-cluster-version/cluster-version-operator-8bb6cff75-7fhxd        Running
Nov 26 14:32:53 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-apiserver/openshift-kube-apiserver        DoesNotExist
Nov 26 14:32:53 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-scheduler/openshift-kube-scheduler-ip-10-0-18-37.ec2.internal        Running
Nov 26 14:34:38 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-apiserver/openshift-kube-apiserver-ip-10-0-43-201.ec2.internal        Pending
Nov 26 14:34:38 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-scheduler/openshift-kube-scheduler-ip-10-0-18-37.ec2.internal        Running
Nov 26 14:34:38 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-controller-manager/openshift-kube-controller-manager-ip-10-0-43-201.ec2.internal        Pending
Nov 26 14:34:38 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-cluster-version/cluster-version-operator-8bb6cff75-7fhxd        Running
Nov 26 14:34:43 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-apiserver/openshift-kube-apiserver-ip-10-0-43-201.ec2.internal        Pending
Nov 26 14:34:43 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-scheduler/openshift-kube-scheduler-ip-10-0-18-37.ec2.internal        Running
Nov 26 14:34:43 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-controller-manager/openshift-kube-controller-manager-ip-10-0-43-201.ec2.internal        Running
Nov 26 14:34:43 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-cluster-version/cluster-version-operator-8bb6cff75-7fhxd        Running
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-scheduler/openshift-kube-scheduler-ip-10-0-18-37.ec2.internal        Running
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-controller-manager/openshift-kube-controller-manager-ip-10-0-43-201.ec2.internal        Running
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-cluster-version/cluster-version-operator-8bb6cff75-7fhxd        Running
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: Pod Status:openshift-kube-apiserver/openshift-kube-apiserver-ip-10-0-43-201.ec2.internal        Running
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: All self-hosted control plane components successfully started
Nov 26 14:34:48 ip-10-0-7-196 bootkube.sh[4235]: Tearing down temporary bootstrap control plane...

And on one of the master nodes I see:
[core@ip-10-0-13-248 ~]$ sudo crictl logs $(sudo crictl ps --pod=$(sudo crictl pods --name=etcd-member --quiet) --quiet)
E1127 08:00:27.762235    3992 remote_runtime.go:278] ContainerStatus "CONTAINER" from runtime service failed: rpc error: code = Unknown desc = container with ID starting with CONTAINER not found: ID does not exist
FATA[0000] rpc error: code = Unknown desc = container with ID starting with CONTAINER not found: ID does not exist 
[core@ip-10-0-13-248 ~]$ sudo crictl pods --name=etcd-member
POD ID              CREATED             STATE               NAME                                      NAMESPACE           ATTEMPT
73e729675f488       17 hours ago        Ready               etcd-member-ip-10-0-13-248.ec2.internal   kube-system         1
0110484f5a685       18 hours ago        NotReady            etcd-member-ip-10-0-13-248.ec2.internal   kube-system         0

**Comment by tzvatot** [comment]
Yes @dgoodwin .
However, I'm still unable to login to the cluster using exported kubeconfig.
```
Error from server (InternalError): an error on the server ("service unavailable") has prevented the request from succeeding (get imagestreams.image.openshift.io)
Error from server (InternalError): an error on the server ("service unavailable") has prevented the request from succeeding (get routes.route.openshift.io)
Error from server (InternalError): an error on the server ("service unavailable") has prevented the request from succeeding (get buildconfigs.build.openshift.io)
Error from server (InternalError): an error on the server ("service unavailable") has prevented the request from succeeding (get deploymentconfigs.apps.openshift.io)
Error from server (InternalError): an error on the server ("service unavailable") has prevented the request from succeeding (get builds.build.openshift.io)
```

**Comment by tzvatot** [comment]
@dgoodwin what do you suggest to do with this issue?

**Comment by dgoodwin** [comment]
Yours looks like a separate issue, yesterday the openshift api server was broken, I am not aware of status but I heard fix was underway. Is it still reproducible?

**Comment by dgoodwin** [comment]
Should be completed now.
