### ISSUE TITLE
Hive limitations on CIDR

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#111]
Seems like hive have limitations/constraints about the CIDR blocks for ServiceCIDR and PodCIDR.
Can you please share what are the limitations? 
Can hive calculate the ServiceCIDR and PodCIDR itself based on the VPCCIDRBlock?

**Comment by dgoodwin** [comment]
It cannot calculate these. We will eventually have validation that can catch any restrictions. Closing this ticket for now, please open in Jira if this becomes a problem.
