### ISSUE TITLE
failing to get passed route53 api

### ISSUE THREAD

**Issue by rayashworth** [openshift/hive#1168]
I've tested my creds using the aws cli as well.  Seem as though something is adding \n in the Credentials.

msg="failed to scrape name servers for domain" controller=dnsendpoint domain=purple-chesterfield.com error="error querying name servers: error querying zone ID: RequestError: send request failed\ncaused by: Get \"https://route53.amazonaws.com/2013-04-01/hostedzonesbyname?dnsname=purple-chesterfield.com.&maxitems=5\": net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=AKI____________MVX**\\n**/20201007/us-east-1/route53/aws4_request, SignedHeaders=host;x-amz-date, Signature=8d2cf337c76a28bc3d506e1a5faf65f0517bd84b7c09066d9a0b9ea20f942343\" for key Authorization" scraper=nameServer 

Here is closest example from someone else.
https://github.com/boto/botocore/issues/2001

**Comment by rayashworth** [comment]
Also opened an forum thread with amazon
https://forums.aws.amazon.com/thread.jspa?threadID=329288

**Comment by rayashworth** [comment]
I setup my hive environment using "make deploy" from the repo.  I started by using hiveutil and then changed to using-hive.  both end up in same error state.

**Comment by rayashworth** [comment]
initial issue was that I did not base64 encode my keys.  This has been corrected in both aws keys and ssh keys.

**Comment by rayashworth** [comment]
I am working from a ubuntu command line and here is my go version
root@Rayvm:/workspace/acm# go version
go version go1.15.2 linux/amd64
root@Rayvm:/workspace/acm#

**Comment by staebler** [comment]
> initial issue was that I did not base64 encode my keys. This has been corrected in both aws keys and ssh keys.
> 
> You may want to add a comment about base64 in the docs when talking about secrets.
> 
> You may also want to note the need for "base64 -w 0" on linux. for ssh keys this will get rid of the newlines.

I would not recommend that anyone do the base64 encoding directly. Either use `kubectl create secret` or fill in the `stringData` fields rather than the `data` fields of the secret.

**Comment by staebler** [comment]
Nothing jumps out to me as wrong in the Authorization header.

**Comment by staebler** [comment]
> Nothing jumps out to me as wrong in the Authorization header.

I take that back. It looks like there may be some superfluous whitespace at the end of the AWS key.
```
Credential=AKI____________MVX**\n**
```
should be just
```
Credential=AKI____________MVX
```

**Comment by rayashworth** [comment]
correct, the \n is what we are trying to figure out, I think.

**Comment by staebler** [comment]
```
oc create secret generic route53-aws-creds -n hive  \
--from-literal=aws_access_key_id=YOUR_ID \
--from-literal=aws_secret_access_key=YOUR_SECRET
```

**Comment by staebler** [comment]
> ```
> kubectl create secret generic route53-aws-creds -n hive  \
> --from-literal=aws_access_key_id=YOUR_ID \
> --from-literal=aws_secret_access_key=YOUR_SECRET
> ```

The YOUR_ID and YOUR_SECRET should be plain text and not encoded.

**Comment by rayashworth** [comment]
I used a secret the I build manual from the OCP admin console, and here is the begging of the log...

time="2020-10-07T20:52:25.401Z" level=info msg="Version: openshift/hive v1.0.11-2-gf81fd52"
time="2020-10-07T20:52:25.401Z" level=info msg="hive namespace: hive"
time="2020-10-07T20:52:25.401Z" level=info msg="Starting /healthz and /readyz endpoints"
time="2020-10-07T20:52:25.401Z" level=info msg="generated leader election ID" id=e0ba8867-cde8-468a-97de-526f4de68c77
I1007 20:52:25.402903       1 leaderelection.go:243] attempting to acquire leader lease  hive/hive-controllers-leader...
I1007 20:52:25.420139       1 leaderelection.go:253] successfully acquired lease hive/hive-controllers-leader
time="2020-10-07T20:52:25.42Z" level=info msg="became leader" id=e0ba8867-cde8-468a-97de-526f4de68c77
I1007 20:52:26.470670       1 request.go:645] Throttling request took 1.046172414s, request: GET:https://172.30.0.1:443/apis/network.openshift.io/v1?timeout=32s
time="2020-10-07T20:52:27.875Z" level=info msg="Registering Components."
time="2020-10-07T20:52:27.877Z" level=info msg="using aws creds for managed domains stored in \"test-aws-secret\" secret" controller=dnsendpoint
time="2020-10-07T20:52:27.878Z" level=info msg="Reapply interval set" reapplyInterval=2h0m0s
time="2020-10-07T20:52:27.878Z" level=info msg="Starting the Cmd."
time="2020-10-07T20:52:27.879Z" level=info msg="started metrics calculator goroutine"
time="2020-10-07T20:52:27.879Z" level=info msg="calculating metrics across all ClusterDeployments" controller=metrics
time="2020-10-07T20:52:27.982Z" level=info msg="ClusterDeployment created" controller=clusterpool
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision
time="2020-10-07T20:52:28.083Z" level=info msg="Job created" controller=clusterProvision

**Comment by rayashworth** [comment]
I am thinking I am over the hump on the aws key issue, but the deployment does not appear to progress.

**Comment by rayashworth** [comment]
> > ```
> > kubectl create secret generic route53-aws-creds -n hive  \
> > --from-literal=aws_access_key_id=YOUR_ID \
> > --from-literal=aws_secret_access_key=YOUR_SECRET
> > ```
> 
> The YOUR_ID and YOUR_SECRET should be plain text and not encoded.

got it, thanks!

**Comment by staebler** [comment]
The `.spec.provisioning.imageSetRef` field in the ClusterDeployment points to a non-existent ClusterImageSet
```
time="2020-10-07T20:55:13.572Z" level=warning msg="clusterdeployment references non-existent clusterimageset" clusterDeployment=hivecluster1 clusterimageset=openshift-v4.5.8 controller=clusterDeployment namespace=hive
```

**Comment by staebler** [comment]
> The `.spec.provisioning.imageSetRef` field in the ClusterDeployment points to a non-existent ClusterImageSet
> 
> ```
> time="2020-10-07T20:55:13.572Z" level=warning msg="clusterdeployment references non-existent clusterimageset" clusterDeployment=hivecluster1 clusterimageset=openshift-v4.5.8 controller=clusterDeployment namespace=hive
> ```

See https://github.com/openshift/hive/blob/master/docs/using-hive.md#openshift-version

**Comment by rayashworth** [comment]
Thanks for all of your responses.

I added correct imageset now.

Wondering about this message.
level=info msg="scrape name servers for domain" controller=dnsendpoint domain=purple-chesterfield.com scraper=nameServer

**Comment by rayashworth** [comment]
what is best way to restart the deployment?

**Comment by dgoodwin** [comment]
Delete the ClusterProvisions to trigger a new attempt I believe would work.

**Comment by rayashworth** [comment]
These messages look good to me.

" level=info msg="Successful validation" group=hive.openshift.io method=validateCreate object.Name=openshift-v4.5.8 operation=CREATE resource=clusterimagesets version=v1
time="2020-10-08T13:21:06Z" level=info msg="Validating request" group=hive.openshift.io method=Validate operation=CREATE resource=clusterprovisions version=v1
time="2020-10-08T13:21:06Z" level=info msg="Successful validation" group=hive.openshift.io method=validateCreateRequest object.Name=hivecluster1-0-zpfks object.Namespace=hive operation=CREATE resource=clusterprovisions version=v1

**Comment by rayashworth** [comment]
I am now seeing a new cluster provisioning pod.

**Comment by rayashworth** [comment]
here is some output from the controller as well.

ime="2020-10-08T13:22:06.027Z" level=info msg="reconciling cluster deployment" clusterDeployment=hivecluster1 controller=clusterDeployment namespace=hive
time="2020-10-08T13:22:06.026Z" level=info msg="reconciling syncidentityproviders and clusterdeployments" NamespacedName=hive/hivecluster1 controller=syncidentityprovider
time="2020-10-08T13:22:06.026Z" level=info msg="reconcile complete" controller=remotemachineset elapsed="78.911µs" machinePool=hivecluster1-worker namespace=hive
time="2020-10-08T13:22:06.026Z" level=info msg="reconciling cluster provision" controller=clusterProvision name=hive/hivecluster1-0-zpfks
time="2020-10-08T13:22:06.027Z" level=info msg="reconcile complete" NamespacedName=hive/hivecluster1 clusterDeployment=hivecluster1 controller=syncidentityprovider elapsed="715.673µs" namespace=hive
time="2020-10-08T13:22:06.026Z" level=info msg="reconciling cluster deployment" clusterDeployment=hive/hivecluster1 controller=clusterState
time="2020-10-08T13:22:06.027Z" level=info msg="reconcile complete" clusterDeployment=hive/hivecluster1 controller=clusterState elapsed="815.664µs"
time="2020-10-08T13:22:06.026Z" level=info msg="reconcile complete" clusterDeployment=hive/hivecluster1 controller=clusterRelocate elapsed="105.543µs"
time="2020-10-08T13:22:06.026Z" level=info msg="reconciling cluster deployment" clusterDeployment=hivecluster1 controller=unreachable namespace=hive
time="2020-10-08T13:22:06.027Z" level=info msg="reconcile complete" clusterDeployment=hivecluster1 controller=unreachable elapsed="948.796µs" namespace=hive
time="2020-10-08T13:22:06.027Z" level=error msg="install pod is stuck" controller=clusterProvision job=hivecluster1-0-zpfks-provision name=hive/hivecluster1-0-zpfks pod=hivecluster1-0-zpfks-provision-mcm99
time="2020-10-08T13:22:06.027Z" level=info msg="The auth for cloud.openshift.com from cluster deployment pull secret is used instead of global pull secret" clusterDeployment=hivecluster1 controller=clusterDeployment namespace=hive
time="2020-10-08T13:22:06.027Z" level=info msg="The auth for quay.io from cluster deployment pull secret is used instead of global pull secret" clusterDeployment=hivecluster1 controller=clusterDeployment namespace=hive
time="2020-10-08T13:22:06.027Z" level=info msg="The auth for registry.connect.redhat.com from cluster deployment pull secret is used instead of global pull secret" clusterDeployment=hivecluster1 controller=clusterDeployment namespace=hive
time="2020-10-08T13:22:06.027Z" level=info msg="The auth for registry.redhat.io from cluster deployment pull secret is used instead of global pull secret" clusterDeployment=hivecluster1 controller=clusterDeployment namespace=hive
time="2020-10-08T13:22:06.027Z" level=info msg="reconcile complete" clusterDeployment=hivecluster1 controller=clusterDeployment elapsed="705.223µs" namespace=hive result="{false 0s}"
time="2020-10-08T13:22:06.036Z" level=info msg="reconcile complete" controller=clusterProvision elapsed=9.401004ms name=hive/hivecluster1-0-zpfks
time="2020-10-08T13:22:28.458Z" level=info msg="calculating metrics across all ClusterDeployments" controller=metrics
time="2020-10-08T13:22:28.458Z" level=info msg="metrics calculation complete" controller=metrics elapsed="506.409µs"
time="2020-10-08T13:22:28.458Z" level=info msg="reconcile complete" controller=metrics elapsed="529.229µs"
time="2020-10-08T13:24:28.458Z" level=info msg="calculating metrics across all ClusterDeployments" controller=metrics
time="2020-10-08T13:24:28.459Z" level=info msg="metrics calculation complete" controller=metrics elapsed="554.891µs"
time="2020-10-08T13:24:28.459Z" level=info msg="reconcile complete" controller=metrics elapsed="589.291µs"
time="2020-10-08T13:26:28.459Z" level=info msg="calculating metrics across all ClusterDeployments" controller=metrics
time="2020-10-08T13:26:28.46Z" level=info msg="metrics calculation complete" controller=metrics elapsed="552.198µs"
time="2020-10-08T13:26:28.46Z" level=info msg="reconcile complete" controller=metrics elapsed="587.06µs"

**Comment by dgoodwin** [comment]
According to the code this means the install pod is stuck in Pending state. Can you check oc describe pod output, and oc get events, suspect something like missing pv's, or bad Secret references.

**Comment by rayashworth** [comment]
now getting this in the provision pod

'/bin/openshift-install' -> '/output/openshift-install.tmp'
'/output/openshift-install.tmp' -> '/output/openshift-install'
total 359636
drwxrwsrwx. 2 root       1000590000        31 Oct  8 13:37 .
drwxr-xr-x. 1 root       root              72 Oct  8 13:37 ..
-rwxr-xr-x. 1 1000590000 1000590000 368267264 Oct  8 13:37 openshift-install

**Comment by rayashworth** [comment]
I did have to resolve a secret name.

**Comment by rayashworth** [comment]
I now see 4 provisioning pods

**Comment by rayashworth** [comment]
also seeing this no in the hive log of the provision pod

time="2020-10-08T13:53:45Z" level=info msg="all files found, ready to proceed" installID=j4nwdfwg
time="2020-10-08T13:53:45Z" level=info msg="copied /output/openshift-install to /home/hive/openshift-install" installID=j4nwdfwg
time="2020-10-08T13:53:45Z" level=info msg="copied /output/oc to /home/hive/oc" installID=j4nwdfwg
time="2020-10-08T13:53:45Z" level=info msg="copying install-config.yaml" installID=j4nwdfwg
time="2020-10-08T13:53:45Z" level=error msg="error reading install-config.yaml" error="open /installconfig/install-config.yaml: no such file or directory" installID=j4nwdfwg
time="2020-10-08T13:53:45Z" level=fatal msg="runtime error" error="open /installconfig/install-config.yaml: no such file or directory"

**Comment by rayashworth** [comment]
i reissued this secret command for the install-config

oc create secret generic install-config-secret --from-file=install-config.yaml=./install-config.yaml

**Comment by rayashworth** [comment]
waiting on next provision to start.

**Comment by rayashworth** [comment]
getting closer...

time="2020-10-08T15:02:24Z" level=info msg="copied /output/oc to /home/hive/oc" installID=fhvdz7p4
time="2020-10-08T15:02:24Z" level=info msg="copying install-config.yaml" installID=fhvdz7p4
time="2020-10-08T15:02:24Z" level=error msg="error adding pull secret to install-config.yaml" error="could not unmarshal InstallConfig: error converting YAML to JSON: yaml: line 34: did not find expected key" installID=fhvdz7p4
time="2020-10-08T15:02:24Z" level=info msg="waiting for files to be available: [/output/.openshift_install.log]" installID=fhvdz7p4
time="2020-10-08T15:02:24Z" level=fatal msg="runtime error" error="could not unmarshal InstallConfig: error converting YAML to JSON: yaml: line 34: did not find expected key"

not sure why I am seeing this. been debugging using a separate secret, but cannot seem to shake it.

**Comment by staebler** [comment]
> time="2020-10-08T15:02:24Z" level=fatal msg="runtime error" error="could not unmarshal InstallConfig: error converting YAML to JSON: yaml: line 34: did not find expected key"

The install config is malformed in some way.

**Comment by rayashworth** [comment]
I used a converter to test what I had.  I was wrapping the pull secret in quot's, looks like that is not good.   Next provision will start at 11:06 Central time.

**Comment by rayashworth** [comment]
got a little farther now...
time="2020-10-08T16:06:33Z" level=debug msg="    Fetching Install Config..."
time="2020-10-08T16:06:33Z" level=debug msg="    Reusing previously-fetched Install Config"
time="2020-10-08T16:06:33Z" level=debug msg="    Fetching Cluster ID..."
time="2020-10-08T16:06:33Z" level=debug msg="    Reusing previously-fetched Cluster ID"
time="2020-10-08T16:06:33Z" level=debug msg="    Fetching Platform Credentials Check..."
time="2020-10-08T16:06:33Z" level=debug msg="    Reusing previously-fetched Platform Credentials Check"
time="2020-10-08T16:06:33Z" level=debug msg="  Generating DNS Config..."
time="2020-10-08T16:06:35Z" level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"hivecluster1.purple-chesterfield.com\": No public route53 zone found matching name \"hivecluster1.purple-chesterfield.com\""
time="2020-10-08T16:06:36Z" level=error msg="error after waiting for command completion" error="exit status 1" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=error msg="error generating installer assets" error="exit status 1" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=info msg="reading installer log" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=info msg="saving installer output" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=debug msg="installer console log: level=info msg=\"Credentials loaded from default AWS environment variables\"\nlevel=info msg=\"Consuming Install Config from target directory\"\nlevel=fatal msg=\"failed to fetch Common Manifests: failed to fetch dependency of \\\"Common Manifests\\\": failed to generate asset \\\"DNS Config\\\": getting public zone for \\\"hivecluster1.purple-chesterfield.com\\\": No public route53 zone found matching name \\\"hivecluster1.purple-chesterfield.com\\\"\"\n" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=info msg="updating clusterprovision" installID=p4g6pcjh
time="2020-10-08T16:06:36Z" level=fatal msg="runtime error" error="exit status 1"

**Comment by rayashworth** [comment]
correcting base domain did the trick.

looks like the deploy is starting pods log looks good so far.

**Comment by rayashworth** [comment]
cluster is at 87% installed.  So, looking very good.

I see my aws instances are running as well.

**Comment by rayashworth** [comment]
Cluster is up and running.  Thanks for all of the responses.   I am thinking the doc for aws secret setup could use a little more detail.  since just copying the yaml and applying it it a little problematic if you dont get the base64 right.

**Comment by gregsheremeta** [comment]
> am thinking the doc for aws secret setup could use a little more detail.

Please submit a PR :)

**Comment by rayashworth** [comment]
I don't have permission to fork the repo.

**Comment by gregsheremeta** [comment]
I've never heard of that before. hive is a public repo, so any account should be able to fork it.

**Comment by rayashworth** [comment]
I now have a fork.
