### ISSUE TITLE
when outputing to yaml from hive util. should --namespace add yaml to create the namespace/project?

### ISSUE THREAD

**Issue by rayashworth** [openshift/hive#1170]
At the moment we are creating the cluster namespace manually.  Is there a reason the hiveutil does not create the cluster namespace for us, when supplying --namespace?

**Comment by rayashworth** [comment]
Sample command line.

 bin/hiveutil create-cluster --base-domain=purple-chesterfield.com --release-image="quay.io/openshift-release-dev/ocp-release:4.5.8-x86_64" --namespace=hivecluster --cloud=aws hivecluster -o yaml > hivecluster.yaml

**Comment by gregsheremeta** [comment]
`-o yaml` implies that nothing will be done to the cluster, so it should definitely not create the namespace.

It might make sense to create the namespace otherwise, but since it's easy enough to do with a one-liner, I don't really see the need. Thanks for the question.

**Comment by rayashworth** [comment]
sure, but just to be clear.  I am using the output yaml.  oc apply -f <yaml> 

Yes, in our ansible automation we will add the create namespace line to overcome the issue.
