### ISSUE TITLE
clusterclaim updates spec.namespace

### ISSUE THREAD

**Issue by hassenius** [openshift/hive#1176]
Just started looking at Hive, and it is indeed a very interesting project. I'm particularly interested in the new clusterpool feature.
However, looking at the current implementation, when I create a `clusterclaim` CR the controller signals back to me which cluster "I have received" by updating `.spec.namespace` However, this approach seems to break with the API convention as outlined for Kubernetes: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md

My intuitive expectation would be to declare my intents in `.spec` and find the "response" in `.status`, so in other words after creating a clusterclaim object I would expect to find the namespace in `.status.namespace` rather than `.spec.namespace`

Am I wrong in my understanding that the current implementation breaks with the api convention?

**Comment by hassenius** [comment]
@dgoodwin @staebler any thoughts on this?

**Comment by dgoodwin** [comment]
Yes Matthew's comment covers why we do this. We've struggled with this in earlier versions of our API and now use status only for what can be observed. It also helps when using backup tooling such as Velero for information that you cannot lose.

**Comment by hassenius** [comment]
Right. It makes sense now that I understand these points. I guess the more simplistic use cases with the core primitives has set embedded a pattern of thinking that may not hold in the more complex scenarios.

Thanks for explaining. Pattern adjusted...
