### ISSUE TITLE
Cluster configuration point of clusterpool

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1178]
The cluster pool has a great cluster pool feature. But I found the cluster from cluster pool has hardcoded the worker node number to 3 and no way to config what kind of EC2 instance to be worker nodes. 

Can anybody let me know how to set the installConfigSecretRef as ClusterDeployment?

**Comment by staebler** [comment]
That feature is not supported. There is currently no customization of the InstallConfig beyond what is offered in the ClusterPool spec.

**Comment by hassenius** [comment]
It seems like the InstallConfigSecretRef is passed directly to the installer without any customizations, making it unsuitable for clusterpool (at minimum there would be a conflict on the cluster name).

Initially it appears this would need to be tackled via a enhancement to the Builder generateInstallConfigSecret https://github.com/openshift/hive/blob/febdb89a829dfc1e20e6a959990d6b6bf15578bc/pkg/clusterresource/builder.go#L313 

Do you know if this is something that is planned for @staebler ?

**Comment by staebler** [comment]
There have been talks of allowing the user to specify an InstallConfig secret to the ClusterPool. But I do not think that any work on such a feature in on the roadmap.

**Comment by hassenius** [comment]
Took a stab at addressing this here: https://github.com/openshift/hive/pull/1182

**Comment by rayashworth** [comment]
My team is in need of this capability as well.
