### ISSUE TITLE
How to export hive data from one ocp cluster and import to another ocp cluster

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1184]
If I need to move from one ocp cluster to an other ocp cluster, how I can export all hive data(cluster, machine pool, clusterpool, clusterclaim etc) from the original ocp cluster to the new ocp cluster, so that new operation can be resumed from the new ocp cluster?

**Comment by dgoodwin** [comment]
Check out the ClusterRelocate API, this is for moving a ClusterDeployment from one Hive to another. Apologies it is not documented today other than the go types.

**Comment by tojosephyang** [comment]
Can you please provide some sample steps and payloads?
