### ISSUE TITLE
Is it possible to move a resource managed by a selectorsyncset into a syncset?

### ISSUE THREAD

**Issue by maleck13** [openshift/hive#1202]
If I have a resource managed by a selectorsyncset and a requirement arises that I need that resource to be unique to a cluster is it possible to migrate the resource from one to the other?

**Comment by maleck13** [comment]
Follow on question. Is it possible to mark a resource as no longer managed by Hive and not have Hive delete the on cluster resource? For example if you wanted an agent on cluster to begin managing a resource and move it out of Hive

**Comment by dgoodwin** [comment]
As of recent builds you can change the resource apply mode from Sync to Upsert, and once in Upsert Hive will not try to cleanup any resources you remove from the syncset, so if you do this, then you can delete the SelectorSyncSet, then create your new SyncSet with the same resource in Sync mode. I think this should work.

For your followup question you can probably use the same mechanism, deploy it with a SyncSet in Upsert mode, then remove it from the Resources list once you know something else has taken over.

cc @abutcher to keep me honest.
