### ISSUE TITLE
ClusterDeployment without aws credentials => uninstall stuck

### ISSUE THREAD

**Issue by cben** [openshift/hive#121]
Might be related to #114 ?  Might also be NOTABUG, PEBKAC :wink:

I created a ClusterDeployment (actually 2 of them) without providing aws credentials — the aws secrets contain:
```
data:
  awsAccessKeyId: null
  awsSecretAccessKey: null
```
Naturally, no cluster got created.
I deleted the ClusterDeployments and now uninstall pods seem stuck.
Logs: https://gist.github.com/cben/3bf9c8c5e4e8c8f207c24b7460b2ee0c
(as can be expected lots of UnauthorizedOperation and AccessDenied...)

**Comment by dgoodwin** [comment]
I assume nothng could be created in AWS, in which case you can force delete by following the instructions here: https://github.com/openshift/hive#troubleshooting-deprovision (step 2 in particular)
