### ISSUE TITLE
Hiveutil does not doc new required vsphere env. variables GOVC_DATACENTER and GOVC_DATASTORE

### ISSUE THREAD

**Issue by chrisahl** [openshift/hive#1249]
I pulled the latest ocm-2.2 branch (commit 702f5fed3a6e64e02e6df2650215be596d4bc01c) and built hiveutil.  Went to run it using an old command that previously worked but it no longer works.  Turns out the document https://github.com/openshift/hive/blob/master/docs/hiveutil.md#create-cluster-on-vsphere does not mention new environment variables that are required when using `--cloud=vsphere`. 

These two variables are now required and should be documented.
GOVC_DATACENTER
GOVC_DATASTORE

**Comment by chrisahl** [comment]
This is still a valid issue

**Comment by chrisahl** [comment]
@dgoodwin Does this need to be converted to Jira?

**Comment by dgoodwin** [comment]
It would certainly help.

**Comment by chrisahl** [comment]
Opened https://issues.redhat.com/browse/HIVE-1490.  Closing this issue
