### ISSUE TITLE
Drop Admin Password From API

### ISSUE THREAD

**Issue by dgoodwin** [openshift/hive#125]
This functionality was recently dropped from the installer in favor of using a static user with an auto-generated password.

We need to revendor the installer, adjust our API to match the change in https://github.com/openshift/installer/pull/771, and I suspect we will need to pull out the admin password generated similar to how we upload the admin kubeconfig after an install. 

CC @jhernand the installer dropped functionality to let you specify the OpenShift admin password and email, is this workable on your side?

**Comment by dgoodwin** [comment]
CC @ericavonb as well who has a cool idea that may help if we have issues around not being able to set admin password.

**Comment by jhernand** [comment]
@dgoodwin It is workable for us, we are setting a hard-coded password now. If you change Hive so that it informs us of the password generated by the installer we can take it.

CC: @zgalor @elad661 @tzvatot

**Comment by dgoodwin** [comment]
Completed.
