### ISSUE TITLE
Grafana Dashboard and alerting examples or recommendations

### ISSUE THREAD

**Issue by raelga** [openshift/hive#1261]
We are about to create a Grafana Dashboard to improve the observability of our current Hive deployment. For that reason, we were wondering if there are any examples available before starting from scratch.

And the same situation for alerting, we were looking for any recommendation on what to check or example alert rules.

If there is no documentation or examples available, we will start working on it and make them publicly available once ready.

Thanks!

**Comment by gregsheremeta** [comment]
moved to https://issues.redhat.com/browse/HIVE-1363
thanks!
