### ISSUE TITLE
How to setup a syncset rule to update resource with undefined object name

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1305]
I would like to install the openshift container storage to the cluster using syncset, One mandatory step is to label all worker and master nodes. All nodes' name are not predefined however syncset or selectorsyncset patches statement requires a definite name of the resource. 
Please help, how to define a syncset or selectorsyncset to update resources without knowing the name of the resource. 

Other than using syncset/selectorSyncSet, is there any other way to trigger bash shell or container to proceed the configuration task?

**Comment by gregsheremeta** [comment]
We have a go microservice in front of hive that dynamically writes out syncsets as needed. You'll need to do something similar.
