### ISSUE TITLE
Offline install OCP

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1374]
Is it possible to let hive create cluster deployment to deploy OCP by using a local registry, aka, offline install OCP?

**Comment by dgoodwin** [comment]
Yes I believe the ACM teams are doing this, I'm not positive how but I believe it just uses the standard release image pullspec, but a content image source in the Hive cluster that redirects to an internal registry.

**Comment by 2uasimojo** [comment]
@osherdp perhaps you can provide further details?

**Comment by osherdp** [comment]
Yes, sure
Assisted installer enables users to install using their offline registries. The user supplies a config-map for mirror-registries which is actually a wrapper to the regular registries.conf file that resides in each node. We make sure to store that file in the node throughout all stages it goes through 
We also have a way to specify URLs for RHCOS ISO images that we need for the installation on baremetal

What's the specific use-case we're talking about?

**Comment by tojosephyang** [comment]
We just want to see if possible to provision an OCP airgap environment by using hive. 
Preconfigure the registry mirroring in each node make sense, however, how to configure Hive to install OCP to the existing prebuilt hosts without provisioning?

**Comment by dgoodwin** [comment]
Prebuilt bare metal hosts? You'll need something more, possibly open cluster manager and the assisted installer + hive integrated within
