### ISSUE TITLE
Support for post-installation hooks

### ISSUE THREAD

**Issue by jhernand** [openshift/hive#139]
We have an use case where we would like to perform additional configuration steps once the cluster has been installerd. These steps will most probably need the _kubeconfig_ of the admin of the cluster to run. Will Hive support this kind of post-install hooks?

CC: @zgalor

**Comment by dgoodwin** [comment]
Can you provide some examples?

**Comment by dgoodwin** [comment]
In general I'm hoping yes, if you have to reach out to the end cluster, ideally Hive will do it. We just need to work together to beat the requirements down into something generic.

**Comment by jhernand** [comment]
Some examples that we have already been asked to support:

- Configure image streams.
- Apply custom branding to the console.
- Create custom cluster roles, for example a role that gives the customer a limited admin capability.
- Add custom Prometheus rules and alerts.

I think that what all those have in common is that they are "programs" that need admin access to the cluster, using just the API. You could maybe consider having something similar to the list of init containers of a pod, so that the user can tell Hive "I want to run this container with this command line, and with access to the kubeconfig of the cluster". That way the post-installation steps can be quite isolated from Hive, and developed independently by the user of Hive. I can, for example, write one post-installation step in Python, another in Go, another in Ruby, etc, without interfering with the Hive code.

**Comment by jhernand** [comment]
The idea of having an operator for this looks reasonable to me. @aweiteka, @mwoodson did you consider creating that kind of operator?

Federation looks interesting as well, but maybe for a more long term future.

@dgoodwin If we use the operator approach, then we will need a mechanism to have that operator deployed as part of the installation of the cluster. Will Hive do that? How will the API look like?

**Comment by dgoodwin** [comment]
Hive will do that (unless we can find a better way to meet your need), it might even be backed by Federation. We don't have a design for it yet so I can't really comment on what the API would look like, I'd need to do some exploring around the data types that are involved with delpoying operators in a cluster today.

Is this a blocker for your side @jhernand ?

**Comment by jhernand** [comment]
It isn't a real blocker today, but it will become a blocker very soon, in the next sprint. We need to provide @aweiteka and @mwoodson with a mechanism that they can use to customize the cluster after installation. If it isn't part of Hive then we will need to invent something, which I'd rather avoid. So, I think it is better if you do consider it a blocker.

**Comment by dgoodwin** [comment]
CC @abutcher @csrwng @joelddiaz  we'll discuss how and when we can find someone to work on this during scrum.

**Comment by aweiteka** [comment]
Operator-based post-install API config management seems consistent with the 4.0 goals we've been tracking. I would prefer to leave federation out of the discussion since it's a significant architecture shift from ansible playbooks run external to the cluster. The requirements include each cluster to have some unique config so we cannot apply the same config across all clusters. I was interested in understanding what role OLM plays in this use case.

**Comment by dgoodwin** [comment]
Ok @csrwng is going to try to start looking into how we can best support this ASAP.

**Comment by dgoodwin** [comment]
Can we get examples of what kind of things you might do with this operator in a cluster that would vary depending on the cluster?

We're going to do a little investigation into Federation because if we build a mechanism to deploy arbitrary operators into clusters, it winds up looking like something dangerously close to federation, and they've specifically asked us not to re-implement federation without talking to the team first. From ops/SD standpoint I doubt much will change, it's still an operator you write being deployed to do what you need to do, it's just the means by which we get it deployed into the cluster.

Config will need to be considered carefully if there are substantial variations per cluster.

Sounds like your operator would be OLM managed, but we're not experts in this area, just getting used to it now.

**Comment by csrwng** [comment]
I've done some investigation on [Federation](https://github.com/kubernetes-sigs/federation-v2/) and it looks like the right fit for what's needed here. 

Assuming that we can handle the joining of the child cluster to the Hive cluster for you automatically, all you would need to do for every artifact that you need created in child clusters is to create a template resource and a placement resource. The template resource describes the resource you want created in every child cluster. This can be a namespace, configmap, deployment, etc. You can see an example configmap template [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/example/sample1/federatedconfigmap-template.yaml). The placement resource tells federation in which clusters to create the artifacts. This can be done by explicitly enumerating cluster names or simply selecting them via labels as described [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#specclusternames-is-not-provided-specclusterselector-is-provided-and-not-empty). This is a [sample placement resource](https://github.com/kubernetes-sigs/federation-v2/blob/master/example/sample1/federatedconfigmap-placement.yaml).

For now, I will focus on the work to automatically federate each child cluster when federation is present.

**Comment by jhernand** [comment]
@csrwng When is federation expected to be part of OpenShift? I mean, will be able to use a solution based on federation by Feb 2019?

**Comment by dgoodwin** [comment]
@aweiteka @mwoodson @jhernand I think you could proceed with development of an operator to run in-cluster and test against 4.0 clusters, and assume that we will deliver a way for this to be deployed automatically by the Hive cluster. Essentially don't treat federation as a blocker while we get the integration sorted out, just start with the operator whenever you can.

**Comment by csrwng** [comment]
@jhernand federation is usable today and we will deploy it to the hive cluster along with the other hive components.

**Comment by aweiteka** [comment]
My only request is that we don't couple too tightly to federation. The architecture may be perfect but right now it introduces yet another change in how we interact with clusters. Its maturity level is concerning.

On the working assumption that operators are the primary way to extend a cluster, I am focused on ensuring OLM, and possibly the Marketplace, is being leveraged to manage operators. How we bootstrap CSVs, and possibly a catalog with subscriptions, is an open question in my mind.

**Comment by dgoodwin** [comment]
Tracking in https://jira.coreos.com/browse/CO-163
