### ISSUE TITLE
RFE: Openstack ClusterPool

### ISSUE THREAD

**Issue by abraverm** [openshift/hive#1440]
Hive ClusterPool is currently supports only AWS, GCP and Azure[1] could it be extended to support Openstack?

[1] https://github.com/openshift/hive/blob/0c2ddbd8f81de9979e123e3bbb027c0775aa5433/docs/clusterpools.md#supported-cloud-platforms

**Comment by dgoodwin** [comment]
I think this is likely possible yes, just have to keep an eye on templating and what can be assumed for the settings for each cluster.

**Comment by 2uasimojo** [comment]
Opened https://issues.redhat.com/browse/HIVE-1661 for this.
