### ISSUE TITLE
Can we kill hive on SNO after the install?

### ISSUE THREAD

**Issue by jarcher** [openshift/hive#1479]
Trying to free up memory on a 32GB machine - was looking at the 1GB utilized by hive.

Is it critical once SNO is up?

**Comment by dgoodwin** [comment]
I do not fully understand the question, typically Hive is installed on a management cluster with ACM and used to provision additional clusters. You would not want to remove it from your management cluster as you would then no longer be able to provision more clusters.

Hive is not installed on SNO clusters.

Unclear what exactly you are testing here.
