### ISSUE TITLE
Azure platform - ability to specify existing VNET for installation

### ISSUE THREAD

**Issue by marouim** [openshift/hive#1480]
Looks like there is no option to specify an existing VNET when installing on Azure. 

Would be nice to be able to specify the VNET in MachinePoolPlatform just like AWS. 

The use case is to be able to instantiate Openshift clusters on private VNET on Azure using Advanced Cluster Management. 

Thanks,

**Comment by 2uasimojo** [comment]
Hi Martin. Sorry, we don't pay much attention to issues in this repo :(

Do you have access to [Jira](https://issues.redhat.com/secure/CreateIssue!default.jspa)? If so, please create a card under the HIVE-* project.

**Comment by 2uasimojo** [comment]
I'll go ahead and close this. If you have trouble with Jira, reopen or reach out directly and we'll figure out a way to get attention to this matter.
