### ISSUE TITLE
How to get OpenShift version out of the ClusterDeployment?

### ISSUE THREAD

**Issue by elad661** [openshift/hive#150]
In UHC, we're looking at the ClusterDeployment's `status.clusterVersionStatus.current.version`, hoping that this would give us the version of OpenShift deployed on the cluster, but the values we're seeing are something like `0.0.1-2018-12-08-172651`.

I assume that this is the version of the Cluster Version Operator, and not OpenShift itself (as this is OpenShift 4, not 0.0.1).

Is there a canonical way to convert this string into an OpenShift version? Is this string expected to always look like this, or to turn into the user facing `4.0.x` style number when OpenShift 4 is GA?

Thanks.

**Comment by elad661** [comment]
cc: @jhernand

**Comment by dgoodwin** [comment]
This comes from the ClusterVersion object in-cluster, CC @smarterclayton, will this eventually be a more user friendly 4.0.x value? (as opposed to what it is today, 0.0.1-...)

**Comment by dgoodwin** [comment]
My cluster this morning is reporting 4.0.0-0.alpha-2019-01-03-031244. Good enough @elad661 ?

**Comment by elad661** [comment]
Sure, this sounds great, thanks!
