### ISSUE TITLE
'Zones' field does not work

### ISSUE THREAD

**Issue by nimrodshn** [openshift/hive#152]
Specifying the **"Zones"** field in the `ClusterDeployment` object should provision the nodes on the specified list of zones, Assuming I understand correctly. However this does not work - for example creating the following deployment:

```
Name:         degas-mtpjc
Namespace:    uhc-development
Labels:       api.openshift.com/id=1F4FyulChH0kFyhSlewODxbjYVV
              api.openshift.com/name=degas
              controller-tools.k8s.io=1.0
Annotations:  <none>
API Version:  hive.openshift.io/v1alpha1
Kind:         ClusterDeployment
...
Spec:
  Cluster UUID:  94d16fa8-3e75-4b0b-a40d-9579c269c5a0
  Config:
    Base Domain:  sdev.devshift.net
    Cluster ID:   degas
    Machines:
      Name:  master
      Platform:
        Aws:
          Iam Role Name:  
          Root Volume:
            Iops:  100
            Size:  32
            Type:  gp2
          Type:    m5.xlarge
      Replicas:    3
      Name:        worker
      Platform:
        Aws:
          Iam Role Name:  TBD
          Root Volume:
            Iops:  100
            Size:  32
            Type:  gp2
          Type:    m5.xlarge
          Zones:
            us-east-1a
....
```

Does not create a single AZ cluster in zone `us-east-1a` **even though** this AZ is available (according to my AWS console - see image below)

![screenshot from 2018-12-30 11-13-54](https://user-images.githubusercontent.com/8366181/50545773-17d98c80-0c24-11e9-8c46-1ff6b911f240.png)

cc: @jhernand @oourfali @tzvatot @dgoodwin

**Comment by dgoodwin** [comment]
https://jira.coreos.com/browse/CO-170
