### ISSUE TITLE
Using syncset to startup a post-install pod

### ISSUE THREAD

**Issue by okeedookee** [openshift/hive#1663]
Hi there, I am considering using syncset to light up a post-install pod to do some further configuration with "oc" commands in a container. Just wondering if this is possible, if yes, how to obtain the oc login token to access the cluster from the pod.

**Comment by abutcher** [comment]
Hey @okeedookee, I think this would be possible. In addition to the pod, you could create a secret that contains a kubeconfig and then mount that secret in the pod spec or reference it to be used as an environment variable from the secret.

The admin kubeconfig for the cluster can be grabbed from the cluster deployment. You could just send the kubeconfig down for the pod to use or create a service account tailored to what the pod needs to do and then create a kubeconfig for that service account.

```
oc get secret -n ${CLUSTER_NAMESPACE} `oc get cd ${CLUSTER_NAME} -n ${CLUSTER_NAMESPACE} -o jsonpath='{ .spec.clusterMetadata.adminKubeconfigSecretRef.name }'` \
   -o jsonpath='{ .data.kubeconfig }' | base64 --decode > ${CLUSTER_NAME}.kubeconfig
```

**Comment by okeedookee** [comment]
Thanks @abutcher actually, I found an easier way, syncset patch the cluster to create an admin service account, and use the new admin service account to start up the pod.
