### ISSUE TITLE
hiveutil failure: error getting OpenAPISchema: no openapi getter 

### ISSUE THREAD

**Issue by droopy4096** [openshift/hive#1678]
1. created account and project
1. enabled `Kubernetes API` for the project
1. created cluster `hive` within the project using `--release-channel=rapid` and `1.22.4-gke.1501`:
1. installed olm:
    ```shell
    operator-sdk olm install
    ```

1. added hive operator:

   ```shell
   kubectl create -f https://operatorhub.io/install/hive-operator.yaml
   ```

1. applied `HiveConfig.yaml`:
  
   ```yaml
   apiVersion: hive.openshift.io/v1
   kind: HiveConfig
   metadata:
     name: hive
   spec:
     logLevel: debug
     targetNamespace: hive
   ```

   ```shell
   kubectl apply -f HiveConfig.yaml
   ```

1. Followed Hive's documentation for GCP setup:

   1. Logged into GCP console
   1. Created service account `hive-operator`  
      * assigned `owner role` 
   1. created a key for SA
   1. picked JSON format
   1. downloaded JSON key for local storage and consumption `hive-operator-sa-key-droopy4096.json`

1. attempted instantiation of a cluster using compiled `hiveutil`:

   ```
   $ export GOOGLE_CREDENTIALS=$(pwd)/../hive-operator-sa-key-droopy4096.json
   $ hiveutil create-cluster --base-domain=somedomain.org.com --cloud=gcp testcluster
   DEBU[0000] Couldn't find install logs provider environment variable. Skipping. 
   INFO[0000] Loading gcp service account                   credsFilePath=/home/username/work/ocp/hive/../hive-operator-sa-key-droopy4096.json
   FATA[0005] Error                                         command=create-cluster error="error getting OpenAPISchema: no openapi getter"
   ```

**Comment by newtonheath** [comment]
Created https://issues.redhat.com/browse/HIVE-1768

**Comment by 2uasimojo** [comment]
@droopy4096 Talking about this today, just procedurally, we'd like to figure out how we communicate with you. Are you able to see https://issues.redhat.com/browse/HIVE-1768? Are you able to comment on it?

**Comment by droopy4096** [comment]
@2uasimojo am I supposed to create an account? At the moment anonymous view does not let me comment

**Comment by 2uasimojo** [comment]
> am I supposed to create an account?

If it's not too much trouble, yes please.
