### ISSUE TITLE
Can't "go get" specific version of the hive api to use from another projects

### ISSUE THREAD

**Issue by celebdor** [openshift/hive#1688]
Hive currently uses a main module defined in:
/go.mod

To help projects that only need to import the APIs, it has a go mod submodule in:
apis/go.mod

The problem is that if you want to pin the imports to specific versions of the API, you get:

```
$ go get github.com/openshift/hive/apis@v1.1.16
go get: module github.com/openshift/hive@v1.1.16 found, but does not contain package github.com/openshift/hive/apis
``` 

The reason for this is that `go mod` logic, when looking for getting a specific tag, it checks the git tags and sees that indeed there is v1.1.16, but for `go mod` that refers to  the main package. Instead, it expects that a separate git tag exists for the apis submodule which, in this case would be `apis/v1.1.16`

You can see an example of this in https://github.com/go-modules-by-example/submodules/tree/master and some related discussion in the first paragraph of:
https://groups.google.com/g/golang-nuts/c/TiPaAUG8ukM/m/rJ6P8IT-BQAJ

**Comment by newtonheath** [comment]
Moved to Jira project: https://issues.redhat.com/browse/HIVE-1766

**Comment by 2uasimojo** [comment]
Closing -- tracking in jira
