### ISSUE TITLE
[RFE] kubectl plugin replacing hiveutil

### ISSUE THREAD

**Issue by abraverm** [openshift/hive#1707]
[Kubectl plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) are easy to develop and simple to distribute with [Krew](https://krew.sigs.k8s.io/) and looks like all `hiveutil` funcationallity could be replicated to a plugin.  `hiveutil`, on other hand, doesn't have a simpe binary release and requires using go and other tooling to make one.

**Comment by 2uasimojo** [comment]
Today you could "install" hiveutil as a kubectl (or more likely oc) plugin by naming the binary `oc-hiveutil` and putting it in your `$PATH` and it ought to Just Work™. So this is a packaging/distribution statement I guess: you're asking for some kind of protocol for the hive team to build and publish it that way (or any way).

While I think the idea of making it a plugin kind of cool, it needs to be noted that hiveutil is not intended for external use, which IMO this kind of thing would encourage. Perhaps we should make that clearer in the [doc](https://github.com/openshift/hive/blob/master/docs/hiveutil.md).

**Comment by abraverm** [comment]
This statement in [using hive](https://github.com/openshift/hive/blob/master/docs/using-hive.md#cluster-provisioning) is misleading:

> Hive comes with an optional hiveutil binary to assist creating the ClusterDeployment and its dependencies. See the [hiveutil documentation](https://github.com/openshift/hive/blob/master/docs/hiveutil.md) for more information.

It is at the begining of the document which seems to encourage using it.

As a user, I would like to see the opposite, kubectl is cumbersome for daily use. For example hivutil could be extednded to simplify the process of getting weburl and password from CD and claims, or getting the live log of openshift installer of a CD.

Would you rather see another repository for this purpose?

**Comment by 2uasimojo** [comment]
> Would you rather see another repository for this purpose?

Certainly not this. `hiveutil` is used internally by the hive codebase to do hive-y things (give https://github.com/openshift/hive/blob/master/pkg/install/generate.go a skim).

I have parlayed this issue into jira card https://issues.redhat.com/browse/HIVE-1772 since we don't really pay attention to gh issues.

**Comment by 2uasimojo** [comment]
We've updated the [doc](https://github.com/openshift/hive/blob/master/docs/hiveutil.md)
