### ISSUE TITLE
What is the difference between hive and hypershift

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#1742]
I can see [hypershift](https://github.com/openshift/hypershift) can also provision clusters on different clouds, can anyone help share the difference of hypershift and hive here? Thanks!

**Comment by 2uasimojo** [comment]
Hypershift is a particular configuration of an OpenShift cluster where the "cloud provider" is actually another cluster, the "machines" are really pods, that kind of thing. From that point of view, hypershift would be able to install into any cloud that could run such a cluster. (I _think_ I've got that right, I'm no expert.)

Hive is a project that knows how to provision OpenShift clusters into various cloud providers.
However, hypershift isn't one of them. Hypershift clusters will be provisioned some other way.

Did that help?

**Comment by gyliu513** [comment]
> Hive is a project that knows how to provision OpenShift clusters into various cloud providers.

Thanks @2uasimojo , but I can see with hypershift, I can also provision OCP clusters into various cloud providers, like AWS, and I think there are more cloud providers are coming, like IBM Cloud etc. Comments?

**Comment by 2uasimojo** [comment]
That would be a better question for the hypershift team.

To my limited understanding, the hypershift operator can be installed on an OCP "hub" cluster hosted on a limited-but-growing number of cloud providers (AWS, Azure, Agent, Kubevirt, and Baremetal if I'm reading the [docs](https://hypershift-docs.netlify.app/how-to/) right). From there you can ask the operator to deploy a "spoke" OCP cluster, and it will carve out the control plane and workers using virtualized "machines" that are actually encapsulated pods/namespaces/other? within the hub cluster.

By contrast, hive understands how to carve out OCP clusters in the traditional fashion where the "machines" are actually VMs from the cloud provider. Hive also [supports multiple providers](https://github.com/openshift/hive/#supported-cloud-providers), and more are being added.

**Comment by gyliu513** [comment]
Good, thanks @2uasimojo . It seems hypershift is more like a multi-tenancy solution for SaaS/public cloud model of OpenShift, as I can see in one hypershift control plane, it can host multiple ocp control planes in different namespaces, and those ocp control planes can provision VMs as worker nodes on different clouds as data plane.

Let me close this one, as I can see they are targeting different user scenarios even there are some function overlap.
