### ISSUE TITLE
aws: default volume settings are invalid on 4.11 (installer failed to load install config)

### ISSUE THREAD

**Issue by jbpratt** [openshift/hive#1790]
A change somewhere within the OpenShift installer has caused drift with the default install-config that `hiveutil` generates for AWS clusters. Using the default storage settings that `hiveutil` supplies leads to an installation (validation) error on the openshift-installer side:

`controlPlane.platform.aws.iops: Invalid value: 100: iops not supported for type gp2, compute[0].platform.aws.iops: Invalid value: 100: iops not supported for type gp2`

```shell
time="2022-06-09T09:19:42Z" level=debug msg="installer console log: level=error msg=failed to fetch Master Machines: failed to load asset \"Install Config\": failed to create install config: invalid \"install-config.yaml\" file: [controlPlane.platform.aws.iops: Invalid value: 100: iops not supported for type gp2, compute[0].platform.aws.iops: Invalid value: 100: iops not supported for type gp2]\n" installID=h8qgqgpx
```

`registry.ci.openshift.org/ocp/release:4.11.0-0.nightly-2022-06-06-201913`

https://github.com/openshift/hive/blob/d6ff743fc72955e76f7b6ae8e6376f6d9de1a200/pkg/clusterresource/aws.go#L20-L22

Switching back to a 4.10 release works with the same install-config. Removing the `iops` field from the generated config or changing to use a different volume type (`io1`) allows for proceeding with a 4.11 build.

This seems to be a recent change introduced as 4.11 nightly builds have been working.

**Comment by 2uasimojo** [comment]
Hi @jbpratt -- would you mind opening this as a Story in the HIVE-* jira project? Thanks!

**Comment by abutcher** [comment]
Closed by https://github.com/openshift/hive/pull/1806
