### ISSUE TITLE
Can I specify the clustermetadata in clusterdeployment spec

### ISSUE THREAD

**Issue by clyang82** [openshift/hive#1824]
Hi, I check the API of `ClusterDeployment`, it supports `ClusterMetadata`
https://github.com/openshift/hive/blob/707d0936358a9d0c9b5da0708b98b69e4777cbbc/apis/hive/v1/clusterdeployment_types.go#L282-L290

I tried to set the `clusterID` and `InfraID` in `ClusterDeployment` Spec. I found the values are overwritten once the OCP cluster is installed.

My Question is can I customize the ClusterID by setting it in `ClusterDeployment` or somewhere? I guessed it cannot, because it cannot guarantee the clusterID is unique. Just double confirm. Thanks.

**Comment by 2uasimojo** [comment]
Your assessment is correct. Those IDs are generated by the installer at install time. The only way hive allows you to "set" that field is if you're adopting a cluster. Though even then I don't think you're allowed an arbitrary value -- it has to come from the cluster you're adopting.

I'll close this issue as answered -- please reopen if you have further questions!

**Comment by clyang82** [comment]
Thanks @2uasimojo for your answer.
