### ISSUE TITLE
No automatic secrets for Service Accounts in Kubernetes 1.24

### ISSUE THREAD

**Issue by garrettthomaskth** [openshift/hive#1832]
When following the instructions from here https://github.com/openshift/hive/blob/master/docs/developing.md#creating-a-kubernetes-in-docker-kind-cluster, my local hive deployment is missing the secret for the hiveadmission service account. This is because I am using the kindest/node:v1.24.0 image, and in Kubernetes 1.24 secrets are not automatically created for service accounts. I receive the following error messages:

`time="2022-07-26T11:42:16Z" level=error msg="Reconciler error" controller=hive-controller error="no kubernetes.io/service-account-token secrets found" name=hive namespace= object=hive reconcileID=e4bf0615-8b9b-41bb-97ed-6579695f22eb`

after creating the secret for this service account

```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: hiveadmission
  annotations:
    kubernetes.io/service-account.name: "hiveadmission"
```
and manually applying it, I get the following error. 

`time="2022-07-26T11:42:56Z" level=error msg="Reconciler error" controller=hive-controller error="no kubernetes.io/service-account-token secrets found" name=hive namespace= object=hive reconcileID=804e4677-a724-49b8-af33-c4acbbbdb5a4`

I resolved this by creating a secret for the hive-controllers service account.

### How to Reproduce:
```
./hack/create-kind-cluster.sh hive
export IMG=localhost:5000/hive:latest
CGO_ENABLED=0 make build image-hive-fedora-dev docker-push deploy
./hack/hiveadmission-dev-cert.sh
```  
* Note: I also had to manually apply the serviceMonitor CRD, see issue [1831](https://github.com/openshift/hive/issues/1831)

### Versions:
Kind node: kindest/node:v1.24.0
Kind version: kind v0.14.0 go1.18.2 linux/amd64
Hive Repository: Master branch https://github.com/openshift/hive/commit/34a0d9062af3e07b5de52553ee8ce0b6a47d316a

**Comment by 2uasimojo** [comment]
/assign @abutcher 

Andrew has agreed to look at this.

**Comment by abutcher** [comment]
Thanks @garrettthomaskth! I've opened #1835 to document creating the secrets when using Kind. I believe we could also determine where we're running in our operator and create the secrets there but this seems appropriate for the time being.
