### ISSUE TITLE
Internal Install using Private Link - Logs

### ISSUE THREAD

**Issue by bailey84j** [openshift/hive#1841]
I am working to investigate why the install is failing but this would be much easier if there was a way of the logs being pulled through a temp private link or a vpc endpoint for the s3 bucket?

**Comment by 2uasimojo** [comment]
Sorry, can you please clarify? Are you already using [this mechanism](https://github.com/openshift/hive/blob/master/docs/using-hive.md#saving-logs-for-failed-provisions) to have install logs uploaded to S3, and are having trouble accessing the S3 bucket; or are you having trouble accessing the logs on the cluster and are looking for a solution like :arrow_up:?

**Comment by abutcher** [comment]
Hey, we have an open RFE ([HIVE-1756](https://issues.redhat.com/browse/HIVE-1756)) to support gathering bootstrap logs for privatelink which has been getting some traction.
