### ISSUE TITLE
Pass skip_provider_registration flag

### ISSUE THREAD

**Issue by NotABugItsAFeature** [openshift/hive#1894]
When trying to create an Openshift cluster in Azure through RedHat ACM I these errors:

```
Original Error: Cannnot register providers: Microsoft.MixedReality, Microsoft.ApiManagement, Microsoft.Search, Microsoft.ContainerInstance, Microsoft.DBforPostgreSQL, Microsoft.AppPlatform, Microsoft.Media, Microsoft.StoragePool, Microsoft.ManagedIdentity, Microsoft.PowerBIDedicated, Microsoft.MachineLearningServices, Microsoft.Cdn, Microsoft.DataLakeStore, Microsoft.Databricks, Microsoft.Management, Microsoft.RecoveryServices, Microsoft.NotificationHubs, Microsoft.ContainerRegistry, Microsoft.AVS, Microsoft.Logic, Microsoft.CognitiveServices, Microsoft.ManagedServices, Microsoft.Kusto, Microsoft.Web, Microsoft.DBforMySQL, Microsoft.HDInsight, Microsoft.StreamAnalytics, Microsoft.DBforMariaDB, Microsoft.DocumentDB, Microsoft.Devices, Microsoft.ServiceFabricMesh, Microsoft.DataProtection, Microsoft.Sql, Microsoft.Maps, Microsoft.EventHub, Microsoft.OperationalInsights, Microsoft.KeyVault, Microsoft.DevTestLab, Microsoft.HealthcareApis, Microsoft.Relay, Microsoft.EventGrid, Microsoft.DesktopVirtualization, Microsoft.TimeSeriesInsights, Microsoft.Automation, Microsoft.ServiceBus, Microsoft.Maintenance, Microsoft.SecurityInsights, Microsoft.DataMigration, Microsoft.OperationsManagement, Microsoft.DataLakeAnalytics, Microsoft.CustomProviders, Microsoft.Cache, Microsoft.BotService, Microsoft.ServiceFabric. Errors were: Cannot register provider Microsoft.MixedReality with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\"
```

The service principal in itself is fine since I can create a cluster with it on the cli and portal.
I've also checked and both the SP and my own account have the same providers registered.
With the skip_provider_registration flag it will no longer error out on this. (it was mentioned in the logs as well)
It's also mentioned this step is only done to verify that the providers are available and to prevent other misleading errors from triggering (like API not found)

How would I be able to pass this flag?

**Comment by abutcher** [comment]
Hello! This is a question better posed to the installer https://github.com/openshift/installer since Terraform is performing this provider registration but I've found that setting an environment variable `ARM_SKIP_PROVIDER_REGISTRATION=true` should be possible to skip this registration. To set this environment variable for a `ClusterDeployment`, populate `cd.spec.provisioning.installerEnv` https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterdeployment_types.go#L264.

I found this environment variable in this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1928841.
