### ISSUE TITLE
Rotating the admin kubeconfig after 10 years

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/hive#1933]
The admin kubeconfigs generated for any new cluster at install time is valid for 10 years. Ref: https://access.redhat.com/solutions/4845381.

How will hive rotate this certificate after 10 years?

**Comment by abutcher** [comment]
I've created a story within our board https://issues.redhat.com/browse/HIVE-2084. I labeled the issue so that we will discuss at our next grooming and we will update this issue once we have. Thanks!

**Comment by abutcher** [comment]
Bookmarking this KCS article with procedure for generating a new admin kubeconfig https://access.redhat.com/solutions/5286371. It is possible that this procedure could be automated by a controller.
