### ISSUE TITLE
Install fails on ClusterRoleBinding

### ISSUE THREAD

**Issue by japhar81** [openshift/hive#1945]
On OKD 4.11 I installed the hive operator from OperatorHub -- tried both the alpha channel and the mce-2.0 channel. Once installed, I created a base HiveConfig;

```yaml
apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  logLevel: debug
  targetNamespace: hive
```

This fails, and pods in my hive namespace are never created. The status on HiveConfig throws this error;

```
    message: |-
      unable to apply asset: config/controllers/hive_controllers_role_binding.yaml: error when applying patch:
      {"metadata":{"$setElementOrder/ownerReferences":[{"uid":"fd49def4-3900-41e6-9a6a-4305e4c2cb5b"}],"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"name\":\"hive-controllers\",\"ownerReferences\":[{\"apiVersion\":\"hive.openshift.io/v1\",\"blockOwnerDeletion\":true,\"kind\":\"HiveConfig\",\"name\":\"hive\",\"uid\":\"fd49def4-3900-41e6-9a6a-4305e4c2cb5b\"}]},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"hive-controllers\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"hive-controllers\",\"namespace\":\"hive\"}]}\n"},"ownerReferences":[{"apiVersion":"hive.openshift.io/v1","blockOwnerDeletion":true,"kind":"HiveConfig","name":"hive","uid":"fd49def4-3900-41e6-9a6a-4305e4c2cb5b"},{"$patch":"delete","uid":"8bb8e669-5c32-42db-9569-6ad0ff5a3b95"}]}}
      to:
      Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
      Name: "hive-controllers", Namespace: ""
      for: "object": error when patching "object": ClusterRoleBinding.rbac.authorization.k8s.io "hive-controllers" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: "": version must not be empty, metadata.ownerReferences.kind: Invalid value: "": kind must not be empty, metadata.ownerReferences.name: Invalid value: "": name must not be empty]
```

**Comment by 2uasimojo** [comment]
Hi @japhar81. We don't work with OKD much (um, ever), but I'll go off and try to create an environment where I can reproduce this. Stay tuned!

**Comment by 2uasimojo** [comment]
Update: I was able to deploy manually on OKD; so this is going to be something to do with the OLM packaging.

**Comment by 2uasimojo** [comment]
Installed from `alpha` (currently `quay.io/openshift-hive/hive:v1.2.3996-500a742`) via OperatorHub and created the HiveConfig with contents as in your OP. Everything worked smoothly. I'm on OKD `4.11.0-0.okd-2023-01-14-152430`.

Based on the error message, it looks like our apply function is only setting the `uid` of the owner. [Here](https://github.com/openshift/hive/blob/73d17d21af54f36ce3a82da35b79c74158582457/pkg/operator/util/apply.go#L100-L106) is the code that sets up that OwnerReference. As you can see, we set up all the fields that the error message is complaining about before we send the object off to be applied. The apply code creates the object if it does not exist. If it does exist, we create a patch to apply the changes.

In this case, based on the fact that the CRB has a `last-applied-configuration`, it appears as though that CRB existed previously -- probably from a previous iteration of the hive-operator's reconcile loop. I'm not sure why it's trying to `$setElementOrder`. Can you please dump me the full manifest of that CRB, as well as the hiveconfig in its current state?

```
oc get clusterrolebinding hive-controllers -o yaml
oc get hiveconfig hive -o yaml
```
