### ISSUE TITLE
Consider tagging submodule "apis"?

### ISSUE THREAD

**Issue by Rick-xuy** [openshift/hive#1961]
I found that package `github.com/openshift/hive/apis/hive/v1` is placed in submodule `github.com/openshift/hive/apis` instead of root module. <br>
However, it seems that submodule `github.com/openshift/hive/apis` is not tagged. According to [Go Modules wiki](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/openshift/hive/apis/hive/v1`, downstream would depends on **pseudo-version** of module `github.com/openshift/hive/apis`.
```
github.com/openshift/hive/apis v0.0.0-20211217134024-32a93e12e129
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `apis/v0.0.1`, `apis/v1.1.16`etc, so that other project can use tag to import this module in go.mod.

**Comment by 2uasimojo** [comment]
This is an interesting idea. However, we don't tag our main branch (anymore) so I'm not sure how much sense it makes to tag the submodule.

I'm curious how you're consuming hive that you are importing the APIs.

**Comment by Rick-xuy** [comment]
Ok, I see. Thanks for your feedback. I didn't notice that main branch is not tagged anymore.
