### ISSUE TITLE
How if Hive released?

### ISSUE THREAD

**Issue by karl-johan-grahn** [openshift/hive#1985]
How is the product released and packaged? There are no releases on this page and the latest tag is from 7 Sep 2021, however there are PRs continuously being merged.

**Comment by 2uasimojo** [comment]
Hi @karl-johan-grahn! Yes, we stopped creating git-based releases from this repo some time ago as you observed. There are a few ways you can get hive:
- [OperatorHub](https://operatorhub.io/operator/hive-operator). Subscribe to the `alpha` channel, which is updated weekly. (The other channels are no longer maintained.)
- As part of [Red Hat Advanced Cluster Management for Kubernetes](https://www.redhat.com/en/technologies/management/advanced-cluster-management).
- Of course, you can always clone the repo and [build it manually](https://github.com/openshift/hive/blob/master/docs/developing.md).

I'll go ahead and close this issue out. Please let us know if you have further questions!
