### ISSUE TITLE
ClusterSync-controller's requeueAfter duration could be insufficient

### ISSUE THREAD

**Issue by fxierh** [openshift/hive#2028]
Hi team, 

I had a thought about the ClusterSync-controller. Please correct me if I'm wrong. 

At the end of the ClusterSync reconcile loop, a reconcile is requeued after a certain duration: 
https://github.com/openshift/hive/blob/6dfd1cf4527c1d4067d4e6f7a294b2a5915e9f25/pkg/controller/clustersync/clustersync_controller.go#L551

which is determined by the r.timeUntilRenew(...) function (which has some randomness):
https://github.com/openshift/hive/blob/6dfd1cf4527c1d4067d4e6f7a294b2a5915e9f25/pkg/controller/clustersync/clustersync_controller.go#L1157-L1164

By the time this duration elapsed and the ClusterSync controller reconciles again, we may (if we reach the below statement instead of finishing the reconcile early) be checking whether we need to renew all SyncSets/SelectorSyncSets by calling the r.timeUntilRenew(...) function again:
https://github.com/openshift/hive/blob/6dfd1cf4527c1d4067d4e6f7a294b2a5915e9f25/pkg/controller/clustersync/clustersync_controller.go#L474

It seems that, although the aforementioned timeUntilRenew duration has already elapsed, this time we may (with a 50% chance) still get timeUntilRenew > 0 and thus conclude that it is still not the time to do a full re-apply.  

The above process, i.e. reconcile (not the time for re-application) -> requeueAfter -> reconcile (not the time for re-application) -> requeueAfter -> ..., could be repeated for a few times.

**Comment by 2uasimojo** [comment]
Really appreciating these issues, @fxierh. Two things:
- Would you mind bringing these up via jira instead of gh?
- Would you like to start proposing the fixes?  No problem if not, but we would welcome the contributions 😁

**Comment by fxierh** [comment]
Hi @2uasimojo,
Ok, I will be using Jira for this one and in the future. Closing this issue. 
I'd also loved to contribute.
