### ISSUE TITLE
Provided SSH keypair not used for bootstrap node

### ISSUE THREAD

**Issue by Nashluffy** [openshift/hive#2158]
## Overview
Hi - we recently ran into an issue during cluster provisioning where the control plane was not coming up. We wanted to SSH into the bootstrap node to get more information. 

We expected to be able to use the key pair we provided in our cluster deployment to access the bootstrap node. This did not work. When we looked at the ignition config in the GCP bucket that the bootstrap node ran, the authorised keys snippet only contained one entry, which was not the public key we provided.

We were able to access the bootstrap node by looking at the terraform state file of the installer as suggested in [the solution here](https://access.redhat.com/solutions/6538661). 

```
$ cat <installation-directory>/.openshift_install_state.json | grep "*tls.BootstrapSSHKeyPair" -A3
```

## Expected
According to [the docs](https://github.com/openshift/hive/blob/master/docs/using-hive.md#ssh-key-pair), the key pair we reference in the ClusterDeployment should be usable to ssh into the bootstrap node.

## Actual
The ssh key pair we provide in `spec.provisioning.sshPrivateKeySecretRef.name` does get added to the authorised keys file in the ignition config.

## Reproduce
1. Create a key pair
```bash
$ ssh-keygen -t ed25519 -m PEM -f ssh-key -N ""
```
2. Create secret for key pair
```bash
$ kubectl create secret generic "ssh-key" \
  --namespace hive \
  --from-file ssh-privatekey=ssh-key \
  --from-file ssh-publickey=ssh-key.pub
```
3. Reference in ClusterDeployment
```yaml
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
...
spec:
...
  provisioning:
    sshPrivateKeySecretRef:
      name: ssh-key
```
4. SSH into bootstrap node _**FAILS**_
```bash
$ ssh -i ssh-key core@<bootstrap-node>
```

**Comment by 2uasimojo** [comment]
[ClusterDeployment.Spec.Provisioning.SSHPrivateKeySecretRef](https://github.com/openshift/hive/blob/903546686f6109e4c0389d72893cf0272a00e2cb/vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go#L251) is a [LocalObjectReference](https://github.com/openshift/hive/blob/f83eba3c8ab4b203e75dfc582d61d4fedf977cd1/vendor/k8s.io/api/core/v1/types.go#L5976) -- we expect to find the secret in the same namespace as the ClusterDeployment. So...

> $ kubectl create secret generic "ssh-key" \
>   --namespace hive \
>   --from-file ssh-privatekey=ssh-key \
>   --from-file ssh-publickey=ssh-key.pub

Is your ClusterDeployment also in namespace `hive`?

Now, arguably we should somehow fail if you specify that secret and we can't find it...

**Comment by Nashluffy** [comment]
Yes, the cluster deployment lives in the same namespace. When I was pulling the key pair that terraform created from inside the provision pod, I saw my own key pair present under /sshkeys/

**Comment by 2uasimojo** [comment]
@patrickdillon can you please advise here? It sounds like hive is correctly laying down the SSH keys under /sshkeys -- does installer know to look there (assuming its wd is /)? Do we expect to be able to use those keys for the bootstrap node?

**Comment by 2uasimojo** [comment]
@patrickdillon bump

**Comment by patrickdillon** [comment]
The ssh key needs to be included in the install config: `installconfig.sshKey`. If one isn't provided, the installer may create one. That could be a possible explanation for this behavior.
