### ISSUE TITLE
Add IBM resource group flag in hiveutil

### ISSUE THREAD

**Issue by bdattoma** [openshift/hive#2250]
Among the pre-requirement steps to create an IBM Cloud, we get redirected to CCOTL ([GH](https://github.com/openshift/cloud-credential-operator/blob/master/docs/ccoctl.md#ibmcloud)) which suggests to use resource-groups when creating Service IDs

`Note: --resource-group-name option is optional, but it is recommended to use to have finer grained access to the resources.`

However, hiveutil doesn't have a flag for resource group, so if we use resource group in the ccotl cmd, then our cluster creation will fail because would not be using the same resource group.

**Comment by 2uasimojo** [comment]
Closing in favor of https://issues.redhat.com/browse/HIVE-2480.

**Comment by bdattoma** [comment]
> Another thing to be aware of: If you use hive's [MachinePools](https://github.com/openshift/hive/blob/master/docs/using-hive.md#machine-pools), there's currently going to be no way to feed that ResourceGroup to them. You'll either need to constrain your use of MachinePools to the default RG, or avoid them altogether (`--skip-machine-pools` in hiveutil) and manage your MachineSets directly on the spoke cluster.

Hello @2uasimojo ! thanks for your reply and for opening the Jira.

I was using hiveutils for starting building our automated script about cluster provisioning, but I moved to applying config YAML.

> I should warn you: with our current workload, we are unlikely to get around to this any time soon. However, we welcome external contributions! And we'll be happy to guide you along the way.


I'd really like to contribute, although my workload won't let me pull myself into this right now, IBM Cloud and ocp installer are new to me so I'd need some time to dig into, try and error etc. But I'll watch the Jira ticket and if I find any time in the next months to look into it, I will.
