### ISSUE TITLE
How to troubleshoot clusterpools?

### ISSUE THREAD

**Issue by deepsm007** [openshift/hive#2282]
It seems there is no official documentation around troubleshooting clusterpools after looking at https://github.com/openshift/hive/blob/master/docs/troubleshooting.md doc.

**Comment by 2uasimojo** [comment]
Thanks for this, @deepsm007. We track stuff in Jira (my excuse for ignoring this for 3mo) so I've opened https://issues.redhat.com/browse/HIVE-2598 for it.
