### ISSUE TITLE
What is the difference of hive with cluster API

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#382]
Can anyone help to show some difference for this project and the https://github.com/kubernetes-sigs/cluster-api ? Why not using cluster api to help manage openshift on different cloud providers?

**Comment by dgoodwin** [comment]
Part of cluster-api is used in-cluster for OpenShift 4, specifically the Machines API which handles creation/scaling of all compute nodes. 

Hive however runs in a centralized management cluster, which knows about many others clusters. cluster-api wasn't as well suited for this use case although we were involved early on in trying to keep the API designed such that it could be, at some point. (specifically around namespacing cluster-api.Cluster)

The predecessor to Hive was openshift/cluster-operator (now abandoned), in that project we tried a couple approaches to using cluster-api Cluster, one where we embedded our desired API into the ProviderSpec, and another where our API wrapped and auto-generated a cluster-api Cluster which our controllers then acted on. The latter approach won out and was in place when we had to transition to Hive for 4.0. 

We stopped this practice when we began Hive as it was not providing value, and adding a lot of complexity. In the future if OpenShift begins using the Cluster types in-cluster, or a compelling case is made for using cluster-api.Cluster in the centralized Hive management cluster, we may revisit, but we're not aware of any reasons to do so now and it hasn't been discussed in awhile.

**Comment by gyliu513** [comment]
Thanks @dgoodwin for the detailed explanation, I saw that openshift also has a project https://github.com/openshift/machine-api-operator , are you using this project for machine operations?

Also, can you please show more detail why cluster api can not full-fill your requirement? There is a new use case document at here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/staging-use-cases.md , and I think those use cases are good enough?

**Comment by gyliu513** [comment]
FYI @xunpan

**Comment by dgoodwin** [comment]
> Thanks @dgoodwin for the detailed explanation, I saw that openshift also has a project https://github.com/openshift/machine-api-operator , are you using this project for machine operations?

Yes I believe that is the repo that handles the Machine portion of cluster-api in 4.

> 
> Also, can you please show more detail why cluster api can not full-fill your requirement? There is a new use case document at here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/staging-use-cases.md , and I think those use cases are good enough?

These use cases look quite a bit closer to what we do, even from the first one. I think we need more context on what you're asking and why however. 

Hive is built with a few constraints in mind, (1) we provision initially with the new openshift-install, (2) we hand off as much day 2 management as possible to the cluster itself (via manipulating APIs in cluster), (3) we have to GA before cluster-api is stable. 

Given there is no cluster-api provider for OpenShift 4.x I assume that you are asking if Hive could become a cluster-api provider. This might be possible, embedding some variant of 4.x install config into cluster-api.Cluster.ProviderSpec, though I need to check with my team where this went wrong on our cluster-operator project as I can't quite remember anymore. 

We would have a bit of a strange situation where the "Cluster" would be defined in the Hive cluster (it might also be sent to the cluster itself if we're talking about a larger cluster-api effort across the whole OpenShift project, potentially replacing the "InfrastructureConfig" CRD we have in-cluster today), but the Machines/MachineSets are in the cluster itself. This might be a non-issue however if you can compose what APIs you use where, and avoid conflicts between the clusters Hive is managing and the Hive cluster's "Cluster" or "Machine" objects themselves.

In the future it's possible there may be cluster-api integrations possible once their API is stable. 

CC @enxebre who leads our cloud-team most closely involved with cluster-api now.
