### ISSUE TITLE
Resource deletion races with MachineAPI actuators

### ISSUE THREAD

**Issue by crawford** [openshift/hive#56]
When the installer attempts to tear down a cluster, it ends up racing with MAO, which is desperately trying to replace the machines that keep getting deleted. The result is that a few machines get recreated before we completely tear down the control plane. The deletion logic in hive doesn't scan for new resources when it runs, so it never sees these new machines and will get stuck trying to delete dependent resources.

I think there are basically two options going forward:

  - Hive/Installer tells MAO (and every future infrastructure operator) to pause before destroying the cluster.
  - The deletion code continually scans for and deletes resources. This process would end once no more resources have been observed.

For what it's worth, I've observed this on both AWS and libvirt.

**Comment by dgoodwin** [comment]
If we reach into cluster to shut things off we'll need admin kubeconfig available to destroy cluster and Hive, which is probably fine, though it should be an optional thing and if it's given we'll try, but errors would be non-fatal for the cases where we're deleting a broken cluster.

If we could continually scan I'd almost prefer that, wiping out the masters first would help, but it's going to get tricky with the master recovery code coming.

**Comment by abhinavdahiya** [comment]
If we can model the delete runners to run untill a required confidence level is reached, successfull delete pass increases the confidence, error can reset it... 

Or something in the lines so that the delete runners are running multiple passess of success untill we can be sure...

**Comment by joelddiaz** [comment]
We're currently filtering for instances with state 'running' https://github.com/openshift/hive/blob/master/contrib/pkg/awstagdeprovision/awstagdeprovision.go#L722 , so I believe we can extend this to also catch anything that is just recently launched by added 'pending'.

**Comment by joelddiaz** [comment]
I haven't had the pleasure of running into the scenario described here (I'll try to set something up locally here), but it would be great if someone could try this out https://github.com/joelddiaz/hive/tree/catch-pending-instances

**Comment by joelddiaz** [comment]
Can we close this out with https://github.com/openshift/hive/pull/58 being merged?

**Comment by crawford** [comment]
Probably. I'll reopen if we have trouble again in the future.
