### ISSUE TITLE
How can I use hive in OCP 4.2?

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#622]
It seems hive is not an official component in OCP 4.2 now, so if I want to use it, I have to follow the guidance https://github.com/openshift/hive/blob/master/docs/install.md , right?

What is the plan to enable Hive in OCP?

**Comment by gyliu513** [comment]
FYI @clyang82

**Comment by dgoodwin** [comment]
Correct you must install from source today. There has been a lot of discussion around releasing it as an operator, but currently this is not planned and rather were planning instead to possibly deliver on-premise as part of a larger project. (which might also require Hive be packaged as it's own operator) If this becomes important let us know, we might be able to revisit the decision.

**Comment by gyliu513** [comment]
Thanks @dgoodwin , so you mean that OCP is now considering to use hive for on-premise OCP? If so, then it would be great! Also what is the plan for this?

**Comment by dgoodwin** [comment]
Yes plan was to include Hive in some kind of on-prem solution and evolve it to meet those use cases. Not sure yet entirely on the full plan to do so.

We'd like to tighten up the Hive API and call it a v1, so please keep an eye out for changes you'd like to see made and let us know. (as you did with the SyncSet questions) We're a little stuck unable to migrate to a v1 as our prod env is not yet on OSD 4 where we have multi-version CRD functionality, but hopefully we can do this soon.
