### ISSUE TITLE
Introduce `dry-run` for hiveutil

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#644]
Any plan to enable `dry-run` for hiveutil? This can help to facilitate the dev process.

**Comment by dgoodwin** [comment]
Is this in relation to the create-cluster subcommand? If so does "-o yaml" meet your needs? That will just print the yaml we would send to the server, but nothing is actually sent.

**Comment by gyliu513** [comment]
@dgoodwin , not only the YAML templates, but I also want to know the work process for the hiveutil.

Just like `helm install --dry-run` at https://helm.sh/docs/helm/#synopsis-3 , it will only simulate the install process but does not do actual install.

**Comment by gregsheremeta** [comment]
any valuable install simulation would first require dry-run support in the OpenShift installer. I'm not aware of any support or any desire for such a thing.

Thank you for the suggestion, but unfortunately this is not a priority item for us.
