### ISSUE TITLE
Any plan to use klog

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#649]
Hive is using logrus but not klog, using klog may have better run time control https://github.com/kubernetes/community/blob/1d747b3720c06e795b0ef6be3cfff71fc13e8b34/contributors/devel/sig-instrumentation/logging.md

@dgoodwin comments? Thanks!

**Comment by dgoodwin** [comment]
No we have not discussed klog as far as I recall, 

WDYT @openshift/openshift-team-hive ?

We've been pretty happy logrus users but klog looks decent.

**Comment by joelddiaz** [comment]
I don't feel too strongly one way or the other, but I haven't really found the need for more granularity in logging besides the error/warn/info/debug that we get from logrus. And I do enjoy using the WithError() wrapper in logrus.

**Comment by twiest** [comment]
What would we gain / lose with klog?

I've honestly never used it (nor glog), so I can't really say one way or
the other.

**Comment by gyliu513** [comment]
I can see the most advantage of `klog` is that I can know where the log is from, i.e. which file and the code line number etc, but for now, it is difficult to analysis the log for hive now:

```
time="2019-11-05T08:32:59Z" level=info msg="metrics calculation complete" controller=metrics elapsed="610.672µs"
time="2019-11-05T08:32:59Z" level=info msg="reconcile complete" controller=metrics elapsed="636.221µs"
```

**Comment by gregsheremeta** [comment]
thank you for the suggestion. No plans to switch at this time.
