### ISSUE TITLE
Hive ignores requested instance type

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#65]
When running a cluster provisioning request, hive ignores the desired instance type, and creates a t2.medium instances instead.

**Comment by dgoodwin** [comment]
Fixed as far as Hive is concerned in next update, but installer work is still needed. See https://github.com/openshift/installer/issues/545 for tracking.

**Comment by cuppett** [comment]
@dgoodwin Can this one be closed now?

**Comment by dgoodwin** [comment]
Should be yes.
