### ISSUE TITLE
Consider release a multi-arch docker image for hive

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#653]
The hive only support running on x86 now, but it does not support POWER and Z platform.

We can use cross compile to build images for POWER and Z but the problem is we cannot do CI/CD for POWER and Z images.

@dgoodwin comments for this?

**Comment by dgoodwin** [comment]
Yeah this is a big challenge, I need to speak to the teams but I am fairly positive we have absolutely no infrastructure for multi-arch builds or CI. 

cc @derekwaynecarr @sdodson @gregsheremeta

**Comment by gyliu513** [comment]
@dgoodwin travis support multi-arch build now https://docs.travis-ci.com/user/multi-cpu-architectures/ , shall we introduce travis to this repo for multi-arch docker image build?

**Comment by dgoodwin** [comment]
I don't know much about what's going on with multi-arch and this effort, will try to rope in some others. CC @eparis @derekwaynecarr @gregsheremeta 

I am fairly confident we have to build everything in our internal CI system so travis is likely not an option, and this would entail larger support in our CI/CD teams.

**Comment by gyliu513** [comment]
@dgoodwin shall we use similar way to create multi-arch build as https://github.com/openshift/oc/pull/153 ?

**Comment by gregsheremeta** [comment]
We do not have capacity for this at this time.
