### ISSUE TITLE
change from dep to go module

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#656]
@dgoodwin what do you think we use go mod for this repo?

**Comment by dgoodwin** [comment]
@openshift/openshift-team-hive am I remembering correctly there was a blocker here? The version of kubernetes we used at the time wasn't compatible with modules? Anyone know if that is resolved now?

**Comment by joelddiaz** [comment]
according to https://github.com/golang/go/wiki/Modules it should be finalized with go 1.14.

looking at the notes it looks like there were significant changes from 1.12 to 1.13.

i would suggest waiting until it ships/stabalizes as we're not currently blocked with our usage of dep.

**Comment by gregsheremeta** [comment]
done
