### ISSUE TITLE
Enable ClusterDeployments support replicas

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#666]
How about adding a field named as `replicas` to `ClusterDeployments`, so that the operators can create multiple clusters with one command?

FYI @dgoodwin

**Comment by dgoodwin** [comment]
Interesting is this a use case that you have? 

There's a huge amount written on the assumption that one cluster deployment represents one cluster. If this is a use case that is necessary though perhaps a higher level CRD would be useful, ClusterDeploymentSet or something like that, which would handle creation of individual ClusterDeployments with identical settings and some kind of generated name / DNS name.

**Comment by gyliu513** [comment]
FYI @berenss Can you please show more insight for this?

+1 to have `ClusterDeploymentSet` which can enable `replicas` for `ClusterDeployment`, so that we can enable customer can create a number of clusters at one time.

**Comment by gyliu513** [comment]
@dgoodwin I was also opening an issue at https://github.com/kubernetes-sigs/cluster-api/issues/1753 to discuss this as well.

**Comment by berenss** [comment]
Hi @dgoodwin - the use case would be:
- I am a cluster admin creating a batch of new clusters, maybe even edge clusters,
- Cluster admin gets handed a list of cluster sizing requirements,
- cluster sizing attributes could be defined in yaml for ease,
- a parameter could be used to quickly build X number of clusters from the single yaml definition,
- I'll be honest that we have not really thought thru the cluster lifecycle implications of batch cluster deploy, but I would expect the new batch of clusters to have the same lifecycle characteristics of any other single cluster that you deploy.

we see this can be useful in edge scenarios, but also in development scenarios where you have a pipeline that builds/deploys to a batch set of clusters for running various test cases.

**Comment by dgoodwin** [comment]
Use case makes sense especially with cloud provider clusters as most of that can be static except for the cluster name and possibly basedomain depending on how you're doing DNS. A little more tricky with our bare metal plans as that would require unique host info in each install-config we'd need to figure out how to generate.

With the V1 API though that install-config will be a little bit problematic. At present, Hive does not ever parse the installconfig, we're looking at possibly having to deal with multiple versions of it coming through and that's not fun with Go serialization. To make this work in Hive we'd need to be taking an install-config template secret, and munging things into it. Not impossible, just ugly and something we were hoping to avoid.

I'm wondering if this is a good Hive API (which it may be, something customers could use, and we have floated the idea in the past), or something to handle with tooling external to Hive, some kind of scripting or a UI codebase.

**Comment by dgoodwin** [comment]
cc @openshift/openshift-team-hive

**Comment by gyliu513** [comment]
@dgoodwin @berenss based on the discussion with cluster api community at https://github.com/kubernetes-sigs/cluster-api/issues/1753#issuecomment-552929113 , they think this is a feature on top of `cluster api` and should belong to a separate project which consume `cluster api`.

For hive, do you think it make sense if we create another CRD `ClusterDeploymentSet` in a separate project to handle this case?

**Comment by dgoodwin** [comment]
It depends a bit on the use cases I think, looking at @berenss comment above, if the goal is just to create a bunch of identical clusters, I'm not sure this makes sense as an API. Rather it would make more sense as a screen in a UI like MCM that just handled the creation for you.

If however it's also involved in the whole lifecycle of those clusters, we scale the set up and down, some settings perhaps can be changed, then we might want to think about an API for it, but there are a lot of questions to be answered about what we're committing to if we're talking about a long lived Set CRD that controls lifecycle of a bunch of clusters.

**Comment by gregsheremeta** [comment]
closing -- should be handled in ACM per above discussion
