### ISSUE TITLE
Hive fails to provision cluster - index out out range error

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#68]
During the process of provisioning a new cluster, hive failed with the following error:

```
Error: Error applying plan:

3 error(s) occurred:

* module.vpc.data.aws_route_table.worker[5]: data.aws_route_table.worker.5: Your query returned no results. Please change your search criteria and try again.
*module.vpc.aws_route.to_nat_gw[5]: index 5 out of range for list aws_route_table.private_routes.*.id (max 5) in:

${aws_route_table.private_routes.*.id[count.index]}
*module.vpc.aws_route_table_association.worker_routing[5]: index 5 out of range for list aws_route_table.private_routes.*.id (max 5) in:

${aws_route_table.private_routes.*.id[count.index]}
```

After re-running it with the same arguments to provision another cluster, it passed this phase successfully. Seems like inconsistent failure.

**Comment by dgoodwin** [comment]
Is this resolved now with the new versions of installer and hive?

**Comment by tzvatot** [comment]
I only did a single cluster provisioning, which didn't had the issue. I will run some more today hopefully and report back.

**Comment by tzvatot** [comment]
Reporting back: I deployed a couple of clusters, and didn't run into this issue.
