### ISSUE TITLE
Any intent to provide vsphere support?

### ISSUE THREAD

**Issue by stobias123** [openshift/hive#714]
see question

**Comment by dgoodwin** [comment]
Nothing planned, but if there's customer demand I think we could, if not we could also take as community contribution.

CC @katherinedube

**Comment by katherinedube** [comment]
It wouldn't be until we add installer provisioned infrastructure support for deploying to VMware vSphere in the OpenShift installer before we would be able to consider it. However, adding more provider support for Hive is something we'd like to do.

**Comment by stobias123** [comment]
@katherinedube 
Is there any intent to add vsphere IPI support to the installer?

**Comment by katherinedube** [comment]
Yes. We're planning to see what can be done early next year to come up with an approach to be able to provide an installer provisioned infrastructure deployment method for vSphere. Unlike public cloud providers where we readily have access to standard DNS and Load Balancer services with a programmatic API, those services aren't available in a vSphere environment (typically, a myriad of customer-managed services are used.) However, those services are needed in order to bootstrap an OpenShift cluster. While non-trivial, it should be able to be solved by leveraging on-cluster DNS & LB services to handle internal cluster communication while integrating with external customer-managed services for ingress communication.

**Comment by reenberg** [comment]
@katherinedube, I hope you also account for disconnected installations.  I assume especially image/content location is one of the things that is special in this scenario.  

I have just found this project, and havent had the time to comprehend all the current features.  So sorry if this is a non issue.

Do you have any information about how this would map with Resource Pools?  I would assume that most enterprises won't supply (vSphere) cluster wide credentials, but only to a specific Resource Pool for this purpose.  And I would also assume that it would be quite useful to be able to control the various users/teams resource usage through mapping to child pools, such that some teams may be allowed to provision more clusters/machines than others.   

I know this is not your direct use case, but my primary use case would be to use Hive to internally offer cluster-as-a-service to teams through something similar to RedHat cluster manager website/api.

**Comment by jaykeshur** [comment]
+1

**Comment by gregsheremeta** [comment]
we are beginning to work on vSphere support now.

**Comment by jaykeshur** [comment]
@gregsheremeta thanks are there any expected timescales on when this will be available (even as alpha)?

**Comment by gregsheremeta** [comment]
@jaykeshur I cannot commit to anything, but we hope for completion by early summer. I'll try to remember to ping you when PRs are up, or feel free to watch the repo.

**Comment by rasheedamir** [comment]
@gregsheremeta I wonder how the vsphere support will work in hive until there is no IPI support in the installer for vpshere?

**Comment by gregsheremeta** [comment]
@rasheedamir I don't fully understand your question, but Hive uses the vsphere IPI support in the installer.

**Comment by rasheedamir** [comment]
If I am not wrong OpenShift 4.4 has only UPI support for vSphere; and still IPI support is missing which is mainly due to lack of DNS & LB services in vSphere

Might be its coming in 4.5 or 4.6; and hive is using those versions for testing?

**Comment by gregsheremeta** [comment]
I can't speak to what version it will GA in OpenShift. 

https://github.com/openshift/installer/blob/master/docs/user/vsphere/install.md

**Comment by rasheedamir** [comment]
This is awesome! We have been waiting for IPI support for quite sometime now

**Comment by katherinedube** [comment]
Installer-provisioned infrastructure support for VMware is planned for the next release.

**Comment by stobias123** [comment]
It looks like this might be possible now... any docs around showing an example cluster deployment? Would love to use this with ACM

**Comment by gregsheremeta** [comment]
No docs yet. See #975 for a hiveconfig example which will generate the ClusterDeployment with `-o yaml`

ACM will use Hive's vSphere support natively.

**Comment by stobias123** [comment]
Hmmm... getting permission denied in hive install container. 

```
'/vsphere/./..data' -> '/etc/pki/ca-trust/source/anchors/./..data'
'/vsphere/./.cacert' -> '/etc/pki/ca-trust/source/anchors/./.cacert'
cp: cannot create symbolic link '/etc/pki/ca-trust/source/anchors/./..data': Permission denied
cp: cannot create symbolic link '/etc/pki/ca-trust/source/anchors/./.cacert': Permission denied
cp: cannot create directory '/etc/pki/ca-trust/source/anchors/./..2020_08_01_02_20_01.633234305': Permission denied
```

Maybe I dont have a proper version of that hive installer image? :(

**Comment by gregsheremeta** [comment]
Please open an issue and include hive version, openshift version, vsphere version, and the steps you took.
