### ISSUE TITLE
Persist install logs for debugging?

### ISSUE THREAD

**Issue by cben** [openshift/hive#72]
Hi.  Currently the main log is the logs of the installer pod.  These have a limited lifetime, and also get trampled if the pod keeps restarting...
Are there any plans to copy them somewhere more persistent?

There are also various other logs that might be of interest — controller's logs (well I guess it could create Events if interesting things happen), bootstrap node logs...

cc @elad661 @tzvatot

**Comment by dgoodwin** [comment]
Note there is kubectl logs -p for previous pod available. 

Ultimately though this should fall to the logging stack deployed in the cluster where Hive is running. This would then just be a deployment concern for where Hive runs in production.
