### ISSUE TITLE
Configured an LDAP identity provider and tried to login: 'error: x509: certificate signed by unknown authority'

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#731]
Deployed a cluster with hive.
Configured LDAP authentication on it (against Active Directory).
Tried to login with a user from LDAP.
Result:
[kni@worker-1 hive]$ oc login -u sasha 
error: x509: certificate signed by unknown authority
[kni@worker-1 hive]$ 

Below with verbose logging:
[kni@worker-1 hive]$ oc login -u sasha --loglevel=10
I1206 14:49:06.959689   22775 loader.go:375] Config loaded from file:  ./hive3.kubeconfig
I1206 14:49:06.960309   22775 round_trippers.go:423] curl -k -v -XHEAD  'https://api.hive3.qe.ocpedge.net:6443/'
I1206 14:49:07.070803   22775 round_trippers.go:443] HEAD https://api.hive3.qe.ocpedge.net:6443/ 403 Forbidden in 110 milliseconds
I1206 14:49:07.070838   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.070844   22775 round_trippers.go:452]     Content-Length: 186
I1206 14:49:07.070849   22775 round_trippers.go:452]     Date: Fri, 06 Dec 2019 14:49:07 GMT
I1206 14:49:07.070853   22775 round_trippers.go:452]     Audit-Id: ba0831f8-6186-402a-a4a3-cf3780f043b6
I1206 14:49:07.070862   22775 round_trippers.go:452]     Cache-Control: no-cache, private
I1206 14:49:07.070866   22775 round_trippers.go:452]     Content-Type: application/json
I1206 14:49:07.070871   22775 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1206 14:49:07.071857   22775 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://api.hive3.qe.ocpedge.net:6443/apis/user.openshift.io/v1/users/~'
I1206 14:49:07.150335   22775 round_trippers.go:443] GET https://api.hive3.qe.ocpedge.net:6443/apis/user.openshift.io/v1/users/~ 200 OK in 78 milliseconds
I1206 14:49:07.150362   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.150367   22775 round_trippers.go:452]     Date: Fri, 06 Dec 2019 14:49:07 GMT
I1206 14:49:07.150372   22775 round_trippers.go:452]     Content-Length: 242
I1206 14:49:07.150376   22775 round_trippers.go:452]     Audit-Id: 2d213b82-0d21-460a-931c-c0c0b394329f
I1206 14:49:07.150389   22775 round_trippers.go:452]     Cache-Control: no-cache, private
I1206 14:49:07.150395   22775 round_trippers.go:452]     Cache-Control: no-store
I1206 14:49:07.150400   22775 round_trippers.go:452]     Content-Type: application/json
I1206 14:49:07.150444   22775 request.go:968] Response Body: {"kind":"User","apiVersion":"user.openshift.io/v1","metadata":{"name":"system:admin","selfLink":"/apis/user.openshift.io/v1/users/system%3Aadmin","creationTimestamp":null},"identities":null,"groups":["system:authenticated","system:masters"]}
I1206 14:49:07.151141   22775 request_token.go:86] GSSAPI Enabled
I1206 14:49:07.151215   22775 round_trippers.go:423] curl -k -v -XGET  -H "X-Csrf-Token: 1" 'https://api.hive3.qe.ocpedge.net:6443/.well-known/oauth-authorization-server'
I1206 14:49:07.167356   22775 round_trippers.go:443] GET https://api.hive3.qe.ocpedge.net:6443/.well-known/oauth-authorization-server 200 OK in 16 milliseconds
I1206 14:49:07.167385   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.167390   22775 round_trippers.go:452]     Audit-Id: 3c9a2c97-27aa-4385-b0b3-02f399215f58
I1206 14:49:07.167396   22775 round_trippers.go:452]     Cache-Control: no-cache, private
I1206 14:49:07.167401   22775 round_trippers.go:452]     Content-Type: application/json
I1206 14:49:07.167412   22775 round_trippers.go:452]     Content-Length: 600
I1206 14:49:07.167421   22775 round_trippers.go:452]     Date: Fri, 06 Dec 2019 14:49:07 GMT
I1206 14:49:07.167562   22775 round_trippers.go:423] curl -k -v -XHEAD  'https://oauth-openshift.apps.hive3.qe.ocpedge.net'
I1206 14:49:07.256608   22775 round_trippers.go:443] HEAD https://oauth-openshift.apps.hive3.qe.ocpedge.net  in 89 milliseconds
I1206 14:49:07.256642   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.256649   22775 request_token.go:438] falling back to kubeconfig CA due to possible x509 error: x509: certificate signed by unknown authority
I1206 14:49:07.256713   22775 round_trippers.go:423] curl -k -v -XGET  -H "X-Csrf-Token: 1" 'https://oauth-openshift.apps.hive3.qe.ocpedge.net/oauth/authorize?client_id=openshift-challenging-client&code_challenge=RUH2PCqywGW2iFRqh3QyQG3QCpUcATQNyZR_I5sViJE&code_challenge_method=S256&redirect_uri=https%3A%2F%2Foauth-openshift.apps.hive3.qe.ocpedge.net%2Foauth%2Ftoken%2Fimplicit&response_type=code'
I1206 14:49:07.284378   22775 round_trippers.go:443] GET https://oauth-openshift.apps.hive3.qe.ocpedge.net/oauth/authorize?client_id=openshift-challenging-client&code_challenge=RUH2PCqywGW2iFRqh3QyQG3QCpUcATQNyZR_I5sViJE&code_challenge_method=S256&redirect_uri=https%3A%2F%2Foauth-openshift.apps.hive3.qe.ocpedge.net%2Foauth%2Ftoken%2Fimplicit&response_type=code  in 27 milliseconds
I1206 14:49:07.284405   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.284963   22775 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://api.hive3.qe.ocpedge.net:6443/api/v1/namespaces/openshift/configmaps/motd'
I1206 14:49:07.301375   22775 round_trippers.go:443] GET https://api.hive3.qe.ocpedge.net:6443/api/v1/namespaces/openshift/configmaps/motd 403 Forbidden in 16 milliseconds
I1206 14:49:07.301390   22775 round_trippers.go:449] Response Headers:
I1206 14:49:07.301411   22775 round_trippers.go:452]     Audit-Id: 3f52e675-4662-48ad-a5eb-dc40541f8d2d
I1206 14:49:07.301416   22775 round_trippers.go:452]     Cache-Control: no-cache, private
I1206 14:49:07.301420   22775 round_trippers.go:452]     Content-Type: application/json
I1206 14:49:07.301424   22775 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1206 14:49:07.301428   22775 round_trippers.go:452]     Content-Length: 303
I1206 14:49:07.301431   22775 round_trippers.go:452]     Date: Fri, 06 Dec 2019 14:49:07 GMT
I1206 14:49:07.301453   22775 request.go:968] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"motd\" is forbidden: User \"system:anonymous\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"openshift\"","reason":"Forbidden","details":{"name":"motd","kind":"configmaps"},"code":403}
F1206 14:49:07.301862   22775 helpers.go:114] error: x509: certificate signed by unknown authority
[kni@worker-1 hive]$ 

The issue is reproducible.

Note that if I deploy a cluster in AWS with openshift-installer instead, there's no problem configuring ldap authentication - I tried with the same ldap server (active directory).

**Comment by gregsheremeta** [comment]
@achuzhoy hi Sasha, is this still an issue or may I close?

**Comment by achuzhoy** [comment]
I switched to another project.
Feel free to close.
I doubt it's related to hive.
