### ISSUE TITLE
hiveadmission logs show "Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid"

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#763]
Got into an issue not being able to edit an existing clusterdeploy.
Tried to remove the "finalizers:" to be able to quickly delete a cd.

Result:
[kni@worker-1 hive]$ oc edit cd ipv6hivecluster2
error: clusterdeployments.hive.openshift.io "ipv6hivecluster2" could not be patched: Internal error occurred: failed calling webhook "clusterdeploymentvalidators.admission.hive.openshift.io": the server is currently unable to handle the request
You can run `oc replace -f /tmp/oc-edit-bc4c1.yaml` to try this update again.

[kni@worker-1 hive]$ oc get pod -n hive
NAME                                READY   STATUS    RESTARTS   AGE
hive-controllers-589cc95664-mtpms   1/1     Running   0          3m49s
hive-operator-765b44956b-8v66f      1/1     Running   0          3m37s
hiveadmission-67cc5dd9d7-lg6k4      1/1     Running   0          4m20s
hiveadmission-67cc5dd9d7-vkbzf      1/1     Running   0          4m38s

[kni@worker-1 hive]$ oc logs hive-controllers-589cc95664-mtpms -n hive|grep error|tail -n 3
time="2019-12-20T16:47:50Z" level=error msg="error removing finalizer" clusterDeployment=ipv6hivecluster2 controller=clusterDeployment error="Internal error occurred: failed calling webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\": the server is currently unable to handle the request" namespace=default
time="2019-12-20T16:49:12Z" level=error msg="could not remove finalizer" controller=remotemachineset error="Internal error occurred: failed calling webhook \"machinepoolvalidators.admission.hive.openshift.io\": the server is currently unable to handle the request" machinePool=ipv6hivecluster2-worker namespace=default
time="2019-12-20T16:49:12Z" level=error msg="error removing finalizer" clusterDeployment=ipv6hivecluster2 controller=clusterDeployment error="Internal error occurred: failed calling webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\": the server is currently unable to handle the request" namespace=default

[kni@worker-1 hive]$ oc logs hiveadmission-67cc5dd9d7-lg6k4 -n hive|tail -n 3
E1220 16:50:15.713946       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid
E1220 16:50:15.714377       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid
E1220 16:50:15.714381       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid

**Comment by achuzhoy** [comment]
Note that the hive was installed a day before.

**Comment by dgoodwin** [comment]
Pretty sure this is a bug our operator should handle, if not the productitself.

**Comment by gregsheremeta** [comment]
@dgoodwin @achuzhoy is this still an issue?
