### ISSUE TITLE
Hive Day 2 MachinePool Management for BareMetal

### ISSUE THREAD

**Issue by dgoodwin** [openshift/hive#765]
Copying from an issue in another repo:

For most cloud providers Hive supports day 2 machine pool management. Machine pools map to one or more cluster-api MachineSets in the target cluster, which may be distributed across AZs. This feature allows you to scale up/down, enable autoscaling, or add/remove new pools of machines.

A MachinePool for AWS example:

items:
- apiVersion: hive.openshift.io/v1
  kind: MachinePool
  metadata:
    name: dgoodwin1-worker
    namespace: hive
  spec:
    clusterDeploymentRef:
      name: dgoodwin1
    name: worker
    platform:
      aws:
        rootVolume:
          iops: 100
          size: 22
          type: gp2
        type: m4.xlarge
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

I would like to confirm we expect to need this functionality in Hive for BareMetal. My understanding is that we likely do as we want to enable autoscaling, we would create an initial InstallConfig with workers scaled to 0, then once provisioned deliver BareMetalHosts via some out of band inventory process build for the customer, and Hive will begin reconciling the MachinePool replicas/autoscaling limits which the in-cluster machine actuator will attempt to satisfy using the available BareMetalHosts.

Can anyone confirm if this is the plan and we should proceed with adding support for this in Hive?
@mhrivnak
mhrivnak commented 20 days ago

I think we'll want to scale each MachineSet so that its size equals the number of matching BareMetalHosts. Doing that locally on the cluster is advantageous. I made a PR adding that behavior to CAPBM and demo'd it on this week's management sprint demo. metal3-io/cluster-api-provider-baremetal#211

I don't think automatic load-based autoscaling makes sense without a lot more planning around the ability to move hosts from one cluster to another and/or the ability to quickly add hosts to a cluster (instead of the usual time-consuming provisioning process). There's been a small amount of discussion on the possibility of one day being able to suspend Nodes during times of reduced load, but I don't think that's on anyone's radar to push forward.

Does a MachinePool ever replace MachineSets in a way that a Deployment replaces ReplicaSets? If so, that sort of re-paving would be particularly expensive in a bare metal world.

What value would a MachinePool bring? I looked for docs to get a background on them but didn't find anything in the repo.
@dgoodwin
Author
dgoodwin commented 19 days ago

    I think we'll want to scale each MachineSet so that its size equals the number of matching BareMetalHosts. Doing that locally on the cluster is advantageous. I made a PR adding that behavior to CAPBM and demo'd it on this week's management sprint demo. metal3-io/cluster-api-provider-baremetal#211

    I don't think automatic load-based autoscaling makes sense without a lot more planning around the ability to move hosts from one cluster to another and/or the ability to quickly add hosts to a cluster (instead of the usual time-consuming provisioning process). There's been a small amount of discussion on the possibility of one day being able to suspend Nodes during times of reduced load, but I don't think that's on anyone's radar to push forward.

    Does a MachinePool ever replace MachineSets in a way that a Deployment replaces ReplicaSets? If so, that sort of re-paving would be particularly expensive in a bare metal world.

I don't think so no, that more similar to MachineSets -> Machine.

    What value would a MachinePool bring? I looked for docs to get a background on them but didn't find anything in the repo.

MachinePool is just an abstraction out of the installer, technically the compute pool in InstallConfig is a MachinePool, though from what I've seen we're using an empty struct there with replicas set to 0 thus far, and scaling things up later.

I'm going to postpone this work until things become more clear.
@dhellmann
dhellmann commented 5 days ago

I can definitely see a combination of @mhrivnak 's approach and using a sync set to add inventory to a cluster as a way to manage machine sets for baremetal. On the other hand, that's going to be completely different from how we do it for any other type of cluster, because users wouldn't update the machine pools in hive but we would want them to be synced correctly (and not shrink the machine set, for example).
@mhrivnak
mhrivnak commented 4 days ago

This is still not clear to me: do MachinePools add value in a bare metal scenario? What's the big picture on how they should be used with bare metal? The obvious concern is that we want to avoid re-paving the hardware, which is far more expensive and time-consuming than replacing MachineSets in a public cloud environment.

**Comment by dgoodwin** [comment]
Still sounding like we're going to postpone implementing this until we're sure we will need it. For now we assume you have one machine pool/set, created at install time.

**Comment by dgoodwin** [comment]
@mhrivnak what's the latest here, do we need to support defining MachineSets in Hive for BareMetal or will the inventory solution be what scales those up and down automatically?

**Comment by mhrivnak** [comment]
Something needs to create a MachineSet. I assume some part of the installer does that?

From there, CAPBM will automatically scale it to match the number of BareMetalHosts. Something will need to annotate the MachineSet to turn on that scaling feature.

Would a MachinePool add value or be a good way to accomplish any of that?

**Comment by dhellmann** [comment]
> Something needs to create a MachineSet. I assume some part of the installer does that?

Yes, we get one MachineSet by default with the installer. The name is "<cluster>-worker-0", so I see "hub-worker-0" in the hub cluster, for example.

> From there, CAPBM will automatically scale it to match the number of BareMetalHosts. Something will need to annotate the MachineSet to turn on that scaling feature.

I think we're going to want ACM to set up that annotation. The installer doesn't know it is running under Hive/ACM. Hive doesn't know that it should enable scaling, unless something tells it. Is there a way for ACM to tell Hive to add the annotation as part of creating the cluster, or do we need it to do that as a separate step?

**Comment by dgoodwin** [comment]
I was hoping the installer manifests would contain the initial MachineSets so we could get hive to hack those up during the install but it doesn't appear they are included.

There is not presently any way in Hive to control the annotations on the remote machine set. We could add it, but having Hive control it via a hive.MachinePool would probably not work out as we'd assume full control over it's parameters, and disabling that and representing in hive just to add an annotation feels like a bad move.

Lets see if ACM has some mechanism to find that machineset and annotate on the next call.

**Comment by dgoodwin** [comment]
In any case I don't think Hive is going to be involved here. Closing this and we will not support MachinePool management for BareMetal.
