### ISSUE TITLE
Replacing "Error" with Warning

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#768]
Upon re-creating a hive cluster, the user gets errors for the existing entities:
[kni@worker-2 hive]$ oc create -f hivecluster6.yaml 
clusterdeployment.hive.openshift.io/ipv6sashacluster6 created
Error from server (AlreadyExists): clusterimagesets.hive.openshift.io "ipv6sashacluster6-imageset" already exists
Error from server (AlreadyExists): secrets "ipv6sashacluster6-aws-creds" already exists
Error from server (AlreadyExists): secrets "ipv6sashacluster6-install-config" already exists
Error from server (AlreadyExists): machinepools.hive.openshift.io "ipv6sashacluster6-worker" already exists

Do we want to consider replacing the string Error with Warning, i.e. is it really Error?

**Comment by staebler** [comment]
That error is coming from `oc`. You told `oc` to create an object that already exists. That is an error.

**Comment by staebler** [comment]
Note that this has nothing to do with Hive other than that you are telling `oc` to create resources that Hive will use.

**Comment by staebler** [comment]
You could look into using `oc apply` instead of `oc create` if the errors bother you.
