### ISSUE TITLE
Please add the OpenShift version of the cluster to the clusterdeployment status

### ISSUE THREAD

**Issue by elad661** [openshift/hive#77]
At the moment, Hive doesn't provide information about which version of OpenShift it installed. It would be very useful to have the exact version that was installed.

**Comment by dgoodwin** [comment]
Agreed. As soon as I can find out where this is I'll get it into the status.

**Comment by joelddiaz** [comment]
I looked into this and couldn't find some definitive way to grab the version info out of the cluster, so I asked and was told this would soon be possible:

> Joel Diaz Today at 2:55 PM
after a cluster is up and running, is there some canonical way to determine the openshift version that is deployed?
1 reply
wking 1 hour ago
there will be soon (via the cluster-version operator and cluster-version).  For now, try https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#check-for-pending-or-crashing-pods

I think we wait until the official way to grab this information becomes available. If we can't wait, then I'd suggest using some combination of the data associated with the cluster-version-operator pod

```
[jdiaz@minigoomba hive (master %=)]$ oc --config kube -n openshift-cluster-version get pods -o yaml | grep image
      - --release-image=registry.svc.ci.openshift.org/openshift/origin-release:v4.0
      image: registry.svc.ci.openshift.org/openshift/origin-release:v4.0
      imagePullPolicy: Always
      image: registry.svc.ci.openshift.org/openshift/origin-release:v4.0
      imageID: registry.svc.ci.openshift.org/openshift/origin-release@sha256:be335de513b7ec6b9ee992d3af2f2cd19f74c946e76a3b2ebbeb318c9cc31ae9

```

**Comment by dgoodwin** [comment]
Couple tips I got from Clayton in https://jira.coreos.com/browse/CO-122, but it didn't look like it was fully populated yet, although the shell of the object was there and we could probably start grabbing the fields, even if they are empty. Would likely benefit from Andrew's code to get connections to remote cluster.

**Comment by joelddiaz** [comment]
feature added in https://github.com/openshift/hive/pull/120
