### ISSUE TITLE
adoption requires cloud credentials

### ISSUE THREAD

**Issue by mhrivnak** [openshift/hive#774]
I ran `make build` and `make deploy` from the v1 branch. I then tried to "adopt" an existing cluster and got an error message about missing AWS credentials. Cloud credentials should not be required for adoption. I saw a similar message if I specified the cloud as "azure" or "gcp".

```
$ bin/hiveutil create-cluster --adopt --adopt-admin-kubeconfig=/tmp/cluster0.config --adopt-cluster-id=cluster0 --adopt-infra-id=cluster0 cluster0
ERRO[0000] Cannot load AWS credentials                  
ERRO[0000] Error                                         error="open /home/mhrivnak/.aws/credentials: no such file or directory"
```

**Comment by mhrivnak** [comment]
I added `--include-secrets=false` to the command and that enabled it to succeed. That causes the create command to skip [this block of code](https://github.com/openshift/hive/blob/5520264/contrib/pkg/createcluster/create.go#L471-L493), which tries to get the cloud credentials by calling `o.cloudProvider.generateCredentialsSecret(o)`

**Comment by staebler** [comment]
Cloud credentials are required for Hive to manage a cluster. The credentials are not used solely during provisioning: The credentials are used for on-going operations and for de-provisioning as well.

**Comment by mhrivnak** [comment]
The docs describe adopting a "kind" cluster for dev purposes, which presumably cannot take advantage of any cloud credentials. Seems like there should be a way to do that without being required to provide credentials.

https://github.com/openshift/hive/blob/v1/docs/developing.md#adopting-clusterdeployments

**Comment by staebler** [comment]
> The docs describe adopting a "kind" cluster for dev purposes, which presumably cannot take advantage of any cloud credentials.

Yes, however, even when adopting a "kind" cluster, the aws creds are required. In the example provided, the "kind" cluster is adopted as an AWS cluster.

**Comment by dhellmann** [comment]
There won't be any cloud credentials for a bare metal cluster. How do we plan to deal with that?

**Comment by mhrivnak** [comment]
> > The docs describe adopting a "kind" cluster for dev purposes, which presumably cannot take advantage of any cloud credentials.
> 
> Yes, however, even when adopting a "kind" cluster, the aws creds are required. In the example provided, the "kind" cluster is adopted as an AWS cluster.

I may be misunderstanding, but it looks in the example like both the hive cluster and the new managed cluster (`cluster1`) are running in kind on a developer's local machine. When you say it is adopted "as an AWS cluster", what does that mean? How would AWS credentials be used in managing it?

**Comment by staebler** [comment]
> There won't be any cloud credentials for a bare metal cluster. How do we plan to deal with that?

The hiveutil command does not yet support bare metal clusters. It does not support creating or adopting bare metal clusters. When the hiveutil command does support bare metal, then it will not ask for any credentials because, as you stated, bare metal does not use credentials.

**Comment by staebler** [comment]
> > > The docs describe adopting a "kind" cluster for dev purposes, which presumably cannot take advantage of any cloud credentials.
> > 
> > 
> > Yes, however, even when adopting a "kind" cluster, the aws creds are required. In the example provided, the "kind" cluster is adopted as an AWS cluster.
> 
> I may be misunderstanding, but it looks in the example like both the hive cluster and the new managed cluster (`cluster1`) are running in kind on a developer's local machine. When you say it is adopted "as an AWS cluster", what does that mean? How would AWS credentials be used in managing it?

The hiveutil command has a `--cloud` flag that defaults to AWS. The ClusterDeployment created by the hiveutil example has a platform of AWS.

**Comment by staebler** [comment]
Note that you are not required to use the hiveutil command. If you would like to adopt a cluster that you would like Hive to treat as a bare metal cluster, then you are free to create the ClusterDeployment and associated resources manually rather than having the hiveutil command create them for you.

**Comment by djzager** [comment]
While this flag (`--include-secrets=false`) is still present on master, it is useless for the purpose of cluster adoption.

> Note that you are not required to use the hiveutil command. If you would like to adopt a cluster that you would like Hive to treat as a bare metal cluster, then you are free to create the ClusterDeployment and associated resources manually rather than having the hiveutil command create them for you.

I would have happily pursued this route, instead of reverting back to a sufficiently old version of hive that would work, if I could find something in the documentation about adopting a cluster that didn't use `hiveutil`. Not certain this note about [adopting ClusterDeployments](https://github.com/openshift/hive/blob/39d1b4f0d41b8d9807092db04f49b20e821e3a25/docs/developing.md#adopting-clusterdeployments) would work against master based on my experience with a minikube cluster.
