### ISSUE TITLE
Error when deploying hive `make deploy` using latest master

### ISSUE THREAD

**Issue by itdove** [openshift/hive#821]
Hi,

I just redeploy the latest master on an existing hive deployment. The previous hive deploy was deployed last Friday and I got this error.

```
deployment.apps/hive-operator unchanged
Error from server: error when creating "STDIN": unsupported role reference kind: ""
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"name\":\"hiveapi-cluster-admin\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"manager-role\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"hiveapi-sa\",\"namespace\":\"hive\"}]}\n"}},"roleRef":{"name":"manager-role"}}
to:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "hiveapi-cluster-admin", Namespace: ""
Object: &{map["kind":"ClusterRoleBinding" "apiVersion":"rbac.authorization.k8s.io/v1" "metadata":map["name":"hiveapi-cluster-admin" "selfLink":"/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/hiveapi-cluster-admin" "uid":"6d05eb70-46fe-11ea-b860-021aed110e05" "resourceVersion":"54229499" "creationTimestamp":"2020-02-04T03:28:35Z" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRoleBinding\",\"metadata\":{\"annotations\":{},\"name\":\"hiveapi-cluster-admin\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"ClusterRole\",\"name\":\"cluster-admin\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"hiveapi-sa\",\"namespace\":\"hive\"}]}\n"]] "subjects":[map["kind":"ServiceAccount" "name":"hiveapi-sa" "namespace":"hive"]] "roleRef":map["apiGroup":"rbac.authorization.k8s.io" "kind":"ClusterRole" "name":"cluster-admin"]]}
for: "STDIN": ClusterRoleBinding.rbac.authorization.k8s.io "hiveapi-cluster-admin" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"manager-role"}: cannot change roleRef
make[1]: *** [deploy] Error 1
 [HIVE INSTALL] FAILURE: Failed to deploy hive
```
I wonder if it is not related to PR https://github.com/openshift/hive/pull/815 or one of the PR recently merged.

I deleted the hiveapi-cluster-admin and re-run but still have error
```
clusterrolebinding.rbac.authorization.k8s.io/hive-operator-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/hiveadmission-hive-hiveadmission unchanged
clusterrolebinding.rbac.authorization.k8s.io/hiveapi-cluster-admin unchanged
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding configured
deployment.apps/hive-operator unchanged
Error from server: error when creating "STDIN": unsupported role reference kind: ""
make[1]: *** [deploy] Error 1
 [HIVE INSTALL] FAILURE: Failed to deploy hive
make: *** [test] Error 2
```

**Comment by dgoodwin** [comment]
Bad commits went in yesterday, fixed in referenced PR.

**Comment by dgoodwin** [comment]
FYI not sure your use case but a major merge took place yesterday, master now has hive's v1 API and a v1alpha1 compatibility layer. This includes the bare metal provisioning work done so far, though this is not operational until #819 and #820 merge.

**Comment by itdove** [comment]
Thx, I will wait the PR to be merge to try again.
FYI: My use case is for our CICD automation. We have a cluster on which we deploy hive in order to create new clusters.

**Comment by dgoodwin** [comment]
Are you building the Hive image from source or using one of our CI images? If so could you clarify which image ref.

**Comment by itdove** [comment]
From source. I do a 'make deploy'.
Do you plan to use github release tag, so we can clone a stable release as for the time being there is only 1 release tag v1alpha1.

**Comment by dgoodwin** [comment]
We do not have any release tagging in play at this time, just rolling releases via git hash to our main environments. The v1alpha1 tag was created this morning and is the last commit prior to the v1 merge.

However if this is for the integration I think it is then that work should all have been targeting the v1 branch, and thus now master. Nothing should have been using v1alpha1.

**Comment by itdove** [comment]
Deploying with your branch git@github.com:dgoodwin/hive.git works but not with master after the merge of #818

**Comment by itdove** [comment]
ok found the issue... I was cloning the v1 branch instead of master and the last update was done on master and not v1.
