### ISSUE TITLE
Update hack scripts to work with latests versions of Kind

### ISSUE THREAD

**Issue by jparrill** [openshift/hive#833]
Hi there,

There is some modifications needed to be done over the `hack/....sh` files to make it work wih kind latests version.

E.G: `kind get kubeconfig-path` does not exists anymore and also the kustomize part is not fully compatible with the latests k8s version.

**Comment by dgoodwin** [comment]
Yes I saw breakage with latest kind awhile back, nobody has had time to investigate yet. We've been using 0.5.1 in meantime.

**Comment by jparrill** [comment]
I'm still working in this PR in order to solve the kind-control-plane machine issue that occurs on hive pull image:

```
root@kind-control-plane:/var/lib/kubelet# crictl pull registry.svc.ci.openshift.org/openshift/hivev1:hive
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "registry.svc.ci.openshift.org/openshift/hivev1:hive": failed to resolve reference "registry.svc.ci.openshift.org/openshift/hivev1:hive": no scope specified for token auth challenge 
```

It's supose to not have any problem pull the image from podman/docker, but seems that there is something there con crictl tool. The related PR is: https://github.com/openshift/hive/pull/834

**Comment by jparrill** [comment]
I think that this could be relevant to know the behaviour of Kind and Hive together: https://github.com/openshift/hive/pull/834#issuecomment-587623422
