### ISSUE TITLE
Attempt to deploy Hive v1alpha on OpenShift 4.3 failed

### ISSUE THREAD

**Issue by mdelder** [openshift/hive#835]
## What I did
```
# sourced my KUBECONFIG
git clone https://github.com/openshift/hive 
git checkout v1
cd hive
DEPLOY_IMAGE=quay.io/rhibmcollab/hive:v1-alpha-latest make deploy
```

## What happened
Deployment failed with error message:
```
The RoleBinding "hiveapi" is invalid: roleRef.kind: Unsupported value: "": supported values: "Role", "ClusterRole"
make: *** [deploy] Error 1
```

## What I expected:

Successful deployment and operational Hive controllers.

**Comment by gregsheremeta** [comment]
I don't know if this will fix your problem, but v1 was merged to master, so you should use master now. We'll get v1 deleted shortly.

**Comment by staebler** [comment]
Yes, this should be resolved in the master branch.

**Comment by mdelder** [comment]
Confirmed that master deployed cleanly with no changes. Thank you!
