### ISSUE TITLE
Question: When using Hive to provision a cluster in AWS, how does one influence the region the cluster lands in?

### ISSUE THREAD

**Issue by benemon** [openshift/hive#847]
If I generate a cluster deployment using the following hiveutil command:

`hiveutil create-cluster --base-domain=my.domain --cloud=aws --creds-file=/home/bholmes/.aws/credentials --ssh-private-key-file=/home/bholmes/.ssh/hive_id_rsa --ssh-public-key-file=/home/bholmes/.ssh/hive_id_rsa.pub --pull-secret-file=pull-secret.json feb -o yaml > my-domain.yaml`

Then I get a list of items which - among other things - contains a base64 encoded inall-config, as well as a ClusterDeployment. The ClusterDeployment contains:

```
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeployment
  ...
  spec:
     ...
    platform:
      aws:
       ...
        region: us-east-1
```

If I change the region here to eu-west-1, then it is mostly ignored by the installer and can lead to some weird errors and inconsistencies at deploy time - mostly because the install-config.yaml contains hardcoded references to us-east-1.

Is there any way currently to influence this from hiveutil? Or do we currently need to decode-update-then recode the install-config before applying it to the hive namespace?

Thanks!

**Comment by dgoodwin** [comment]
Could have sworn we had --region but it looks like it's gone. The install config pools and hive pools should generally match, especially with big things like region, otherwise you will get pretty dramatic cycling of workers post-install. In this case I think you need to decode that install config like you said to ensure it has the right region. (or patch hiveutil)

**Comment by benemon** [comment]
Thanks @dgoodwin, that clears up that little mystery. As I know sweet FA about Go, I'll resign myself to decoding the install config for now :+1:

**Comment by dgoodwin** [comment]
I'll file a Jira and see if we can get it readded at some point.
