### ISSUE TITLE
Is it planned for Hive to provide information about the nodes once the cluster is deployed?

### ISSUE THREAD

**Issue by elad661** [openshift/hive#85]
It would be really useful for us (the SD-A team) to get information about the nodes once the cluster is deployed - a list of nodes, their types, IP addresses, their OS version and their container runtime version. All of information is in the output of `oc get nodes -o wide`

I was wondering if it's planned for Hive to provide this information in the ClusterDeployment object of a deployed cluster.

**Comment by cben** [comment]
I think in Cluster Operator some (but not all) of this info was gleanable from MachineSet / Machine objects?
But new installer creates machines in Terraform and doesn't report back as objects, right?

random unbaked idea: perhaps Hive could operate k8s federation to sync the inner Node objects outside?

**Comment by dgoodwin** [comment]
The plan was for a caller to use the kubeconfig we store to hit the cluster's api itself. However if you think it's a better fit for Hive we can discuss.

Will mention it to the federation v2 folks we've been talking with for other purposes. Not sure if it syncs in reverse like that.
