### ISSUE TITLE
Hive and Velero: how to?

### ISSUE THREAD

**Issue by yaroslavkasatikov** [openshift/hive#875]
May you please create or share docs how to use velero with hive installed cluster?
I'm unable to find it into repo, but I found 'velero' in go/yaml  so I think you have a solution for using velero with hive.

**Comment by dgoodwin** [comment]
@twiest could we get this documented? 

I think most of the work is complete we just wanted to round out with some testing and docs, but haven't had time yet.

**Comment by twiest** [comment]
@dgoodwin sorry for the delay on this, I keep forgetting to update this issue.

There is a card for this in Jira, it just needs to get added to a sprint.
