### ISSUE TITLE
log redaction too aggressive for multi-line output from installer

### ISSUE THREAD

**Issue by dhellmann** [openshift/hive#878]
The bare metal installer uses ssh to connect to a hypervisor for creating the bootstrap VM. When used with hive, we require an ssh key that does not have a passphrase. If the user provides a key that does require a passphrase, the installer emits a message that includes the word "password", and so the error is redacted. The error message is actually several lines long, and only the last line includes "password" in the list of possible authentication methods. When I run the installer by hand, I see:

```
$ SSH_AUTH_SOCK= setsid ./openshift-baremetal-install create cluster --log-level=debug
dhellmann@dell-r630-008:hive1 (git:multiple-clusters:dd409a5)$ DEBUG OpenShift Installer 4.5.0-0.ci-2020-03-05-200317
DEBUG Built from commit c9fb0963e6a058137ca07817cc181d49cf931a59
DEBUG Fetching Terraform Variables...
DEBUG Loading Terraform Variables...
DEBUG   Loading Cluster ID...
DEBUG     Loading Install Config...
DEBUG       Loading SSH Key...
DEBUG       Loading Base Domain...
DEBUG         Loading Platform...
DEBUG       Loading Cluster Name...
DEBUG         Loading Base Domain...
DEBUG         Loading Platform...
DEBUG       Loading Pull Secret...
DEBUG       Loading Platform...
FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
```

In the logs from the hive provision pod, this comes out looking like

```
$ oc logs -f hive1-0-lfg69-provision-6tfkw -c hive
time="2020-03-03T19:56:07Z" level=debug msg="checking for SSH private key" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=debug msg="checking for SSH private key" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="initializing ssh agent with 2 keys" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=debug msg="no SSH_AUTH_SOCK defined. starting ssh-agent" installID=hfrzwj4b
Enter passphrase for /tmp/ssh-privatekey: time="2020-03-03T19:56:07Z" level=error msg="failed to add private key: /tmp/ssh-privatekey" error="exit status 1" installID=hfrzwj4b key=/tmp/ssh-privatekey
time="2020-03-03T19:56:07Z" level=info msg="ssh agent is not initialized" error="exit status 1" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="waiting for files to be available: [/output/openshift-install /output/oc]" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="found file" installID=hfrzwj4b path=/output/openshift-install
time="2020-03-03T19:56:07Z" level=info msg="found file" installID=hfrzwj4b path=/output/oc
time="2020-03-03T19:56:07Z" level=info msg="all files found, ready to proceed" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="copying install-config.yaml" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="waiting for files to be available: [/output/.openshift_install.log]" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="copied /installconfig/install-config.yaml to /output/install-config.yaml" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="Wrote known hosts to /home/hive/.ssh/known_hosts" installID=hfrzwj4b knownHosts="[|1|ks0j8Qe591bg/AkoB79qHNE1z4Q=|Q1yDytZSpMsfLMNtqy1LhIN4xdE= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCh5D3FqClxnEZGZiZD9fclaVjkzZ98UX+xSBt+v4Q3ashpVhtYda61UTUmbXh9u8J44bYO5DS+OKtbDiBqQSB6p6VuxcIfjvapasUt7awAZIwBMUs2nYA9YA7F+0qpl14M+iK0zdbTqXhDn/KWfGxMK7YhZwPdmHNXV8V3B7yqmpc1skm3B4F5jgMWtY+a80e609SCtyVUaiRwibNILEvFM4YEMng9W9VAhweo1c4wt/hcwbLLQdu+XLrr+56WOy+9Ns9dfJBV4cHyV6Oflb1c2jcG/+FE+1jE1qpADP/lMaX9IPyil8sfPpBRWmpmy2La5pX8Wpc3zfMiz1VcYLAJ |1|FjY8XxC2v4nJOTcgeTiYuGbbRb4=|SRbnfgXHi1n470dgQCMbJT3xmbA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKWjJRzeUVuZs4yxSy4eu45xiANFIIbwE3e1aPzGD58x/NX7Yf+S8eFKq4RrsfSaK2hVJyJjvVIhUsU9z2sBJP8= |1|H5E31tvEAqxqJu9rQBD+l0gsr0g=|k4dMfkdlECjdk5RJEwV/w8ygMFA= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIByDGt93ltGsuJWupi40PEn2VtiYuWw0/Bx2d9PYN1pQ]"
time="2020-03-03T19:56:07Z" level=info msg="cleaning up from past install attempts" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=debug msg="object does not exist" installID=hfrzwj4b object=hive1/hive1-0-lfg69-admin-kubeconfig
time="2020-03-03T19:56:07Z" level=debug msg="object does not exist" installID=hfrzwj4b object=hive1/hive1-0-lfg69-admin-password
time="2020-03-03T19:56:07Z" level=warning msg="skipping cleanup as no infra ID set" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="generating assets" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="running openshift-install create manifests" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=info msg="running openshift-install binary" args="[create manifests]" installID=hfrzwj4b
time="2020-03-03T19:56:08Z" level=info msg="found file" installID=hfrzwj4b path=/output/.openshift_install.log
time="2020-03-03T19:56:08Z" level=info msg="all files found, ready to proceed" installID=hfrzwj4b
time="2020-03-03T19:56:07Z" level=debug msg="OpenShift Installer unreleased-master-2642-g58ecac34ae25797f62fb10504982a8b4562fdaf7-dirty"
time="2020-03-03T19:56:07Z" level=debug msg="Built from commit 58ecac34ae25797f62fb10504982a8b4562fdaf7"
time="2020-03-03T19:56:07Z" level=debug msg="Fetching Master Machines..."
time="2020-03-03T19:56:07Z" level=debug msg="Loading Master Machines..."
time="2020-03-03T19:56:07Z" level=debug msg="  Loading Cluster ID..."
time="2020-03-03T19:56:07Z" level=debug msg="    Loading Install Config..."
time="2020-03-03T19:56:07Z" level=debug msg="      Loading SSH Key..."
time="2020-03-03T19:56:07Z" level=debug msg="      Loading Base Domain..."
time="2020-03-03T19:56:07Z" level=debug msg="        Loading Platform..."
time="2020-03-03T19:56:07Z" level=debug msg="      Loading Cluster Name..."
time="2020-03-03T19:56:07Z" level=debug msg="        Loading Base Domain..."
time="2020-03-03T19:56:07Z" level=debug msg="        Loading Platform..."
time="2020-03-03T19:56:07Z" level=debug msg="      Loading Pull Secret..."
time="2020-03-03T19:56:07Z" level=debug msg="      Loading Platform..."
REDACTED LINE OF OUTPUT
time="2020-03-03T19:56:09Z" level=error msg="error after waiting for command completion" error="exit status 1" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=error msg="error generating installer assets" error="exit status 1" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=info msg="reading installer log" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=info msg="saving installer output" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=debug msg="installer console log: REDACTED LINE OF OUTPUT\n" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=info msg="updating clusterprovision" installID=hfrzwj4b
time="2020-03-03T19:56:09Z" level=fatal msg="runtime error" error="exit status 1"
```

Note that around line 4 of that output is the message `Enter passphrase for /tmp/ssh-privatekey:` but the actual error message is replaced with `REDACTED LINE OF OUTPUT`.

It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately. That would result in output something like this:

```
FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
Permission denied, please try again.
REDACTED LINE OF OUTPUT
```

**Comment by staebler** [comment]
> It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately.

That is already how it works. The entire following text is one line from the installer.

```
FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
```

**Comment by staebler** [comment]
Would any of the following help?
1) Re-evaluate our redaction process to allow more text through un-redacted.
2) Fail earlier if the baremetal ssh key could not be added.
3) Raise the failure to add the ssh key as a failure reason in the clusterdeployment conditions.

**Comment by dhellmann** [comment]
> > It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately.
> 
> That is already how it works. The entire following text is one line from the installer.
> 
> ```
> FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
> Permission denied, please try again.
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
> ```

It's not 1 line. It seems to all be collected as 1 string, but there are newlines embedded in it.

**Comment by dhellmann** [comment]
> Would any of the following help?
> 
> 1. Re-evaluate our redaction process to allow more text through un-redacted.
> 2. Fail earlier if the baremetal ssh key could not be added.
> 3. Raise the failure to add the ssh key as a failure reason in the clusterdeployment conditions.
> 
> Personally, I think that all 3 could and should be done.

It's a failure to be able to use the key, not to add it. Testing that would require understanding the field in install-config.yaml that implies it is needed, parsing the user and host out of the URL, then trying to make an ssh connection there. That's all possible, of course. Ideally the installer would do that so Hive doesn't have to.

**Comment by dhellmann** [comment]
> > > It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately.
> > 
> > 
> > That is already how it works. The entire following text is one line from the installer.
> > ```
> > FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
> > Permission denied, please try again.
> > Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
> > ```
> 
> It's not 1 line. It seems to all be collected as 1 string, but there are newlines embedded in it.

I think it's here: https://github.com/openshift/hive/blob/master/pkg/installmanager/installmanager.go#L919

If the result of reading that was split into lines and each was handled individually, I think that would improve the output as I describe.

**Comment by staebler** [comment]
> > > It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately.
> > 
> > 
> > That is already how it works. The entire following text is one line from the installer.
> > ```
> > FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
> > Permission denied, please try again.
> > Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
> > ```
> 
> It's not 1 line. It seems to all be collected as 1 string, but there are newlines embedded in it.

There are not newlines embedded into it. There is the text "\n" but that is not a newline. By the time it gets to you as the end user something has (incorrectly) converted the "\n" to a newline.

**Comment by dhellmann** [comment]
> > > > It would be easier to debug this failure if the output from the installer was logged 1 line at a time, and each line was redacted separately separately.
> > > 
> > > 
> > > That is already how it works. The entire following text is one line from the installer.
> > > ```
> > > FATAL failed to fetch Terraform Variables: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.baremetal.libvirtURI: Internal error: could not connect to libvirt: virError(Code=38, Domain=7, Message='Cannot recv data: Permission denied, please try again.
> > > Permission denied, please try again.
> > > Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer')
> > > ```
> > 
> > 
> > It's not 1 line. It seems to all be collected as 1 string, but there are newlines embedded in it.
> 
> There are not newlines embedded into it. There is the text "\n" but that is not a newline. By the time it gets to you as the end user something has (incorrectly) converted the "\n" to a newline.

I think we're not talking about the same thing.

The normal log output from the installer is processed one line at a time. The text I'm interested is not part of that. It is emitted from the ssh code triggered by the libvirt C library and sent to stderr for the installer. It ends up in the console log, not the log that is tailed. The console log is processed as a single string, even though it has multiple lines of text.

**Comment by gregsheremeta** [comment]
hi @dhellmann! Does #882 take care of this issue?

**Comment by dhellmann** [comment]
Yes, I think we can close this.
