### ISSUE TITLE
Some `hive-controller-manage` messages contain `ERROR: logging before flag.Parse`

### ISSUE THREAD

**Issue by jhernand** [openshift/hive#88]
Some of the messages in the log of the `hive-controller-manager` pod contain the `ERROR: logging before flag.Parse`, for example:

```
ERROR: logging before flag.Parse: W1120 11:25:50.863560       1 reflector.go:341] github.com/openshift/hive/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1alpha1.DNSZone ended with: The resourceVersion for the provided watch is too old.
```

This is confusing. In the above example it looks like an error, but it is actually a warning. Can this prefix be removed?

**Comment by dgoodwin** [comment]
@csrwng thoughts? 

It looks like an expected periodic thing from Kube, and I don't think we have much control over it due to glog.

**Comment by jhernand** [comment]
The `W1120 ...` error message is fine, what I am asking is if we can remove the `ERROR: logging before flag.Parse` part. I think there is a way to do it.
