### ISSUE TITLE
Fatal error  could not watch MachinePoolNameLeases

### ISSUE THREAD

**Issue by slopezz** [openshift/hive#881]
We have been using openshift hive for a while to provision our dev OCP clusters.

Today we were creating a new`ClusterDeployment`, when we got the following error on the provision installer pod:
```
time="2020-03-09T19:01:43Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.3.3: 99% complete"
time="2020-03-09T19:02:42Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.3.3: 99% complete"
time="2020-03-09T19:04:13Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.3.3: 100% complete, waiting on authentication, console"
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

At them same time we have seen that hive-controllers components was on `CrashLoopBackOff` state:
```
$ kubectl get pods
NAME                                          READY   STATUS             RESTARTS   AGE
dev-eng-ocp4-3-test-0-kzrsw-provision-7vw86   1/3     Running            0          41m
hive-controllers-68f9c55884-w4dcc             0/1     CrashLoopBackOff   7          7d7h
hive-operator-f7db77845-clnb2                 1/1     Running            2          7d8h
hiveadmission-7c6f4fd77b-sxs97                0/1     Running            0          7d8h
hiveadmission-7c6f4fd77b-wm9g9                0/1     Running            0          7d8h
```

Showing the following error on logs:
```
$ kubectl logs -f hive-controllers-68f9c55884-w4dcc
time="2020-03-09T19:10:47Z" level=info msg="Registering Components."
time="2020-03-09T19:10:47Z" level=info msg="no managed domains configured" controller=dnsendpoint
time="2020-03-09T19:10:47Z" level=fatal msg="could not watch MachinePoolNameLeases: no matches for kind \"MachinePoolNameLease\" in version \"hive.openshift.io/v1\""
```

I have deleted the pod, in order to k8s recreate it, but keeps saying the same message.

I have seen there is a new CRD `MachinePoolNameLease` https://github.com/openshift/hive/blob/master/config/crds/hive_v1_machinepoolnamelease.yaml (committed 4 days ago), so I guess the error comes from here (we are using version from  branch: `master`,  commit: `f95446d21ae47da6689f8de91c9b1463955223b7`, which means using generic image `openshift/hive-v4.0:hive`):
```
$ kubectl get MachinePoolNameLeases
error: the server doesn't have a resource type "MachinePoolNameLeases"
```

* Is there a proper way to update current hive deployment version without breaking any deployed cluster? 
* I guess image `openshift/hive-v4.0:hive` is always pointing to `master`. Maybe having an specific GitHub release pointing to a specific image version tag (not a generic `openshift/hive-v4.0:hive` that can introduce issues on working hive deployments?)

**Comment by dgoodwin** [comment]
Looks like you're running the CI hive image which is floating and always updated on each master merge, but you have no automation around re-deploying new CRDs added. You need to re-run make deploy to update and get the new CRs. (make install would be another option that just installs CRDs)

**Comment by slopezz** [comment]
@dgoodwin yes, we are using the default image provided by the `make deploy` target, after re-executing it again, everything is back to normal (`MachinePoolNameLeases` CRD has been created).

Is there any way to know other image tags than the default CI floating `hive-v4.0:hive` (to not break accidentally current deployments because not having hive deployment 100% updated with `master` branch)?

We already saw that some weeks ago you created the GitHub release `v1alpha1`, so we guess `v1`is about to come.

**Comment by dgoodwin** [comment]
There is not presently any way though some discussions underway may result in some more static repeatable images. You would need to roll your own solution, build and push your own hive image somewhere perhaps.

v1 is already master, v1alpha1 was just a tag prior to when we merged master into v1 so we could easily locate it.

**Comment by dgoodwin** [comment]
Also there is a hive operator underway which would likely solve this as well.

cc @gregsheremeta
