### ISSUE TITLE
Any plan to support openstasck and VMWare

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#889]
Hi @dgoodwin , may I know if you have any plan to enable Hive support openstasck and VMWare?

**Comment by dgoodwin** [comment]
I believe so yes, we plan to start on openstack and RHV next sprint, VMware some time in future, probably not far out.

**Comment by gyliu513** [comment]
Thanks @dgoodwin , any issues opened for those requirements? If there are issues, can you help provide some links for me to check more?

Not clear about the sprint time for hive here, can you show me some clear date for this, thanks!  :-)

**Comment by dgoodwin** [comment]
Plz ping on slack and I can send you the internal links in Jira.
