### ISSUE TITLE
Cluster Deprovision job runs indefinitely when Cluster Provisioning fails

### ISSUE THREAD

**Issue by hazim1093** [openshift/hive#923]
Hi,

I am trying to create a cluster on AWS, hive successfully creates EC2 instances, load balancers and other resources but the masters fail to bootstrap with errors logged in the machine config logs. 

After this failure, the cluster is destroyed, all resources are deleted and no ClusterDeprovision resource is found in the management cluster but AWS resources related to the provisioned cluster are cleaned out.

Upon deleting `ClusterDeployment`, a deprovision job is run and it gets stuck in a loop trying to find and delete resources in AWS, as they do not exist. If I try to delete the deprovision job it creates another one and the cycle continues.

The [troubleshooting](https://github.com/openshift/hive/blob/master/docs/troubleshooting.md#deprovision) doesn't help in this case either as resources are already deleted.

**Comment by dgoodwin** [comment]
Assuming we're focusing on the deprovision job, is this a NoSuchHostedZone error?

**Comment by hazim1093** [comment]
Yes, it's the error with `NoSuchHostedZone`.

**Comment by dgoodwin** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1817201 and this fix is now picked up in Hive, if you update to latest master you should be good to go.

**Comment by gregsheremeta** [comment]
@hazim1093 if you're using the operatorhub.io release, we'll update that early next week to include the fix

**Comment by hazim1093** [comment]
@gregsheremeta yes, great 👍 Would love to try it as soon as it's out

**Comment by staebler** [comment]
Fixed in #915.

/close
