### ISSUE TITLE
make: *** [Makefile:263: install-tools] Error 1

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#926]
Attempt to run make deploy results in:
[kni@provisionhost-0-0 hive]$ make deploy
go install -mod=vendor k8s.io/code-generator/cmd/deepcopy-gen
build flag -mod=vendor only valid when using modules
make: *** [Makefile:263: install-tools] Error 1
[kni@provisionhost-0-0 hive]$ 

last git commit I see in my git clone: 383c3c2ff471c793ae73cf495e1d785a6104a865

**Comment by achuzhoy** [comment]
[kni@provisionhost-0-0 hive]$ go install k8s.io/code-generator/cmd/deepcopy-gen
can't load package: package k8s.io/code-generator/cmd/deepcopy-gen: cannot find package "k8s.io/code-generator/cmd/deepcopy-gen" in any of:
        /usr/lib/golang/src/k8s.io/code-generator/cmd/deepcopy-gen (from $GOROOT)
        /home/kni/go/src/k8s.io/code-generator/cmd/deepcopy-gen (from $GOPATH)

**Comment by dgoodwin** [comment]
The recent move to Go modules now requires go 1.13+

**Comment by gregsheremeta** [comment]
works for me in go 1.14.1
```
$ git log | head -1             
commit 383c3c2ff471c793ae73cf495e1d785a6104a865
$ export GOFLAGS=-mod=vendor
$ export GO111MODULE=on
$ make deploy
$ oc get pods -n hive      
NAME                               READY   STATUS    RESTARTS   AGE
hive-controllers-59499b969-fxjhq   1/1     Running   0          6m57s
hive-operator-7b7f6fc44d-ft7dx     1/1     Running   0          8m18s
hiveadmission-5c9b9787d4-9qxvs     1/1     Running   0          6m49s
hiveadmission-5c9b9787d4-kmgwx     1/1     Running   0          6m49s
```
