### ISSUE TITLE
go version required for hive needs to be updated.

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#928]
go version 1.12 doesn't work anymore.
I can confirm that it worked for me with https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz

Note that before running make deploy, I also needed to run: go mod vendor

**Comment by staebler** [comment]
@achuzhoy What changes were made when you ran `go mod vendor`? All of the dependencies should already be vendored.

**Comment by achuzhoy** [comment]
[kni@provisionhost-0-0 hive]$ go mod vendor
go: downloading k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
go: downloading k8s.io/kubernetes v1.14.1
go: downloading k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible
go: downloading github.com/aws/aws-sdk-go v1.29.24
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: downloading k8s.io/cli-runtime v0.0.0-20190409023024-d644b00f3b79
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/openshift/installer v0.9.0-master.0.20200331173433-d200b241c184
go: downloading sigs.k8s.io/controller-runtime v0.2.0-beta.3
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: downloading golang.org/x/sys v0.0.0-20191206220618-eeba5f6aabab
go: downloading github.com/Azure/go-autorest v13.0.0+incompatible
go: downloading github.com/openshift/generic-admission-server v1.14.0
go: downloading github.com/jteeuwen/go-bindata v3.0.8-0.20151023091102-a0ff2567cfb7+incompatible
go: downloading github.com/spf13/cobra v0.0.5
go: downloading golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: downloading google.golang.org/api v0.13.0
go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
go: downloading k8s.io/utils v0.0.0-20190607212802-c55fbcfc754a
go: downloading k8s.io/code-generator v0.0.0-20190311093542-50b561225d70
go: downloading github.com/docker/go-healthcheck v0.1.0
go: downloading github.com/Azure/go-autorest/autorest v0.9.3
go: downloading k8s.io/component-base v0.17.1
go: downloading github.com/Azure/azure-sdk-for-go v38.1.0+incompatible
go: downloading github.com/golangci/golangci-lint v1.23.8
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading github.com/Azure/go-autorest/autorest/to v0.3.1-0.20191028180845-3492b2aff503
go: downloading github.com/openshift/api v0.0.0-20190627141250-de5ca909c732
go: downloading github.com/openshift/cluster-network-operator v0.0.0-20190207145423-c226dcab667e
go: downloading github.com/googleapis/gnostic v0.3.1
go: downloading k8s.io/apiserver v0.0.0-20190409021813-1ec86e4da56c
go: downloading github.com/prometheus/client_golang v0.9.2
go: downloading github.com/docker/docker v0.7.3-0.20190410184157-6d18c6a06295
go: downloading golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/prometheus/common v0.6.0
go: downloading github.com/miekg/dns v1.1.15
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.4.1
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/google/gofuzz v1.1.0
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading github.com/openshift/cluster-api-provider-aws v0.2.1-0.20200316201703-923caeb1d0d8
go: downloading google.golang.org/appengine v1.6.5
go: downloading github.com/json-iterator/go v1.1.8
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: downloading github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/openshift/library-go v0.0.0-20200106191802-9821002633e8
go: downloading k8s.io/kube-openapi v0.0.0-20190425185145-07b897206552
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/vmware/govmomi v0.22.2
go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: downloading github.com/openshift/cluster-api-provider-azure v0.1.0-alpha.3.0.20200120114645-8a9592f1f87b
go: downloading github.com/gregjones/httpcache v0.0.0-20190611155906-901d90724c79
go: downloading cloud.google.com/go v0.49.0
go: downloading github.com/openshift/cluster-autoscaler-operator v0.0.0-20190521201101-62768a6ba480
go: downloading gopkg.in/AlecAivazis/survey.v1 v1.8.9-0.20200217094205-6773bdf39b7f
go: downloading github.com/openshift/cluster-api v0.0.0-20191129101638-b09907ac6668
go: downloading k8s.io/gengo v0.0.0-20190907103519-ebc107f98eab
go: downloading github.com/openshift/cloud-credential-operator v0.0.0-20200316201045-d10080b52c9e
go: downloading golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: downloading github.com/stretchr/testify v1.4.0
go: downloading k8s.io/cluster-registry v0.0.6
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading github.com/go-logr/logr v0.1.0
go: downloading k8s.io/kube-aggregator v0.0.0-20190409022021-00b8e31abe9d
go: downloading github.com/chai2010/gettext-go v0.0.0-20160711120539-c6fed771bfd5
go: downloading github.com/jonboulle/clockwork v0.1.0
go: downloading github.com/gofrs/flock v0.0.0-20190320160742-5135e617513b
go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
go: downloading github.com/dimchansky/utfbom v1.1.0
go: downloading github.com/emicklei/go-restful v2.10.0+incompatible
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.3.1
go: downloading github.com/Azure/go-autorest/autorest/adal v0.8.1-0.20191028180845-3492b2aff503
go: downloading github.com/openshift/cluster-api-provider-gcp v0.0.1-0.20200120152131-1b09fd9e7156
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/openshift/machine-api-operator v0.2.1-0.20200310180732-c63fa2b143f0
go: downloading github.com/golang/groupcache v0.0.0-20191027212112-611e8accdfc9
go: downloading github.com/mattn/go-isatty v0.0.10
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/heptio/velero v1.0.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/getsentry/raven-go v0.2.0
go: downloading github.com/pborman/uuid v1.2.0
go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
go: downloading github.com/fatih/camelcase v1.0.0
go: downloading k8s.io/cloud-provider v0.0.0-20190409023720-1bc0c81fa51d
go: downloading gomodules.xyz/jsonpatch/v2 v2.0.0
go: downloading github.com/certifi/gocertifi v0.0.0-20190506164543-d2eda7129713
go: downloading google.golang.org/grpc v1.25.1
go: downloading github.com/spf13/viper v1.6.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading github.com/hashicorp/golang-lru v0.5.3
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading github.com/coreos/go-systemd/v22 v22.0.0
go: downloading go.opencensus.io v0.22.2
go: downloading github.com/golangci/dupl v0.0.0-20180902072040-3e9179ac440a
go: downloading honnef.co/go/tools v0.0.1-2019.2.3
go: downloading github.com/go-openapi/spec v0.19.3
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/sourcegraph/go-diff v0.5.1
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: downloading github.com/pkg/profile v1.3.0
go: downloading github.com/golangci/revgrep v0.0.0-20180526074752-d9c87f5ffaf0
go: downloading mvdan.cc/unparam v0.0.0-20190720180237-d51796306d8f
go: downloading github.com/go-lintpack/lintpack v0.5.2
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/pelletier/go-toml v1.4.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/timakin/bodyclose v0.0.0-20190930140734-f7f2e9bca95e
go: downloading github.com/golangci/maligned v0.0.0-20180506175553-b1d89398deca
go: downloading github.com/golangci/gofmt v0.0.0-20190930125516-244bba706f1a
go: downloading github.com/go-openapi/jsonreference v0.19.2
go: downloading github.com/uudashr/gocognit v1.0.1
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/munnerz/goautoneg v0.0.0-20190414153302-2ae31c8b6b30
go: downloading github.com/golangci/ineffassign v0.0.0-20190609212857-42439a7714cc
go: downloading github.com/OpenPeeDeeP/depguard v1.0.1
go: downloading github.com/imdario/mergo v0.3.8
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading github.com/jirfag/go-printf-func-name v0.0.0-20191110105641-45db9963cdd3
go: downloading github.com/golangci/misspell v0.0.0-20180809174111-950f5d19e770
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/tommy-muehle/go-mnd v1.1.1
go: downloading github.com/gostaticanalysis/analysisutil v0.0.0-20190318220348-4088753ea4d3
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading github.com/ultraware/whitespace v0.0.4
go: downloading github.com/securego/gosec v0.0.0-20200103095621-79fbf3af8d83
go: downloading github.com/golangci/check v0.0.0-20180506172741-cfe4005ccda2
go: downloading github.com/golang/protobuf v1.3.2
go: downloading sigs.k8s.io/structured-merge-diff v0.0.0-20190302045857-e85c7b244fd2
go: downloading github.com/bombsimon/wsl/v2 v2.0.0
go: downloading github.com/openshift/kubernetes-sigs-controller-tools v0.1.10-0.20190430113700-72ae52c08b9d
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/golangci/goconst v0.0.0-20180610141641-041c5f2b40f3
go: downloading github.com/ultraware/funlen v0.0.2
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/docker/go-units v0.4.0
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/jingyugao/rowserrcheck v0.0.0-20191204022205-72ab7603b68a
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/go-critic/go-critic v0.4.1
go: downloading github.com/go-toolsmith/astfmt v1.0.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/Azure/go-autorest/autorest/validation v0.2.1-0.20191028180845-3492b2aff503
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/google/btree v1.0.0
go: downloading github.com/NYTimes/gziphandler v1.1.1
go: downloading google.golang.org/genproto v0.0.0-20200122232147-0452cf42e150
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/go-openapi/swag v0.19.5
go: downloading github.com/golangci/gocyclo v0.0.0-20180528134321-2becd97e67ee
go: downloading github.com/golangci/lint-1 v0.0.0-20191013205115-297bf364a8e0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading github.com/golangci/unconvert v0.0.0-20180507085042-28b1c447d1f4
go: downloading golang.org/x/mod v0.2.0
go: downloading github.com/go-toolsmith/astp v1.0.0
go: downloading github.com/stretchr/objx v0.2.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/matoous/godox v0.0.0-20190911065817-5d6d842e92eb
go: downloading github.com/go-toolsmith/astequal v1.0.0
go: downloading github.com/mailru/easyjson v0.0.0-20190626092158-b2ccc519800e
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/golangci/errcheck v0.0.0-20181223084120-ef45e06d44b6
go: downloading github.com/kisielk/gotool v1.0.0
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/go-toolsmith/astcopy v1.0.0
go: downloading sourcegraph.com/sqs/pbtypes v0.0.0-20180604144634-d3ebe8f20ae4
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading sigs.k8s.io/kustomize v2.0.3+incompatible
go: downloading mvdan.cc/interfacer v0.0.0-20180901003855-c20040233aed
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/docker/spdystream v0.0.0-20181023171402-6480d4af844c
go: downloading github.com/coreos/etcd v3.3.18+incompatible
go: downloading github.com/go-toolsmith/astcast v1.0.0
go: downloading github.com/prometheus/client_model v0.0.0-20191202183732-d1d2010b5bee
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: downloading mvdan.cc/lint v0.0.0-20170908181259-adc824a0674b
go: downloading github.com/golangci/go-misc v0.0.0-20180628070357-927a3d87b613
go: downloading github.com/golangci/prealloc v0.0.0-20180630174525-215b22d4de21
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/markbates/inflect v1.0.4
go: downloading github.com/onsi/gomega v1.8.1
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading github.com/nbutton23/zxcvbn-go v0.0.0-20180912185939-ae427f1e4c1d
go: downloading sigs.k8s.io/testing_frameworks v0.1.2-0.20190130140139-57f07443c2d4
go: downloading github.com/go-toolsmith/typep v1.0.0
go: downloading github.com/go-toolsmith/strparse v1.0.0
go: downloading github.com/gobuffalo/envy v1.7.0
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/rogpeppe/go-internal v1.3.0
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading go.uber.org/atomic v1.5.1
go: downloading go.uber.org/multierr v1.4.0
go: downloading go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
[kni@provisionhost-0-0 hive]$

**Comment by staebler** [comment]
Are there any changes under the hive directory after that? I think that is just pulling the code into your local cache and is not necessary to build or deploy Hive.
