### ISSUE TITLE
Hive creates a cluster: missing 1 worker node

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#95]
When creating a cluster we provide 6 worker nodes. However, hive created only 5 worker nodes. Does the master considered a worker node as well?

**Comment by dgoodwin** [comment]
Can you paste specifics on what you submitted, ideally oc get clusterdepoyment X -o yaml

**Comment by tzvatot** [comment]
Sure:
`$ oc get clusterdeployments/elad2111b-h262p -o yaml
apiVersion: hive.openshift.io/v1alpha1
kind: ClusterDeployment
metadata:
  annotations:
    hive.openshift.io/delete-after: 8h
  clusterName: ""
  creationTimestamp: 2018-11-21T13:07:46Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-11-21T21:08:29Z
  finalizers:
  - hive.openshift.io/deprovision
  generateName: elad2111b-
  generation: 4
  labels:
    api.openshift.com/id: 1DIZe3ejD8xMid6Vkn9NJD5CqZP
    api.openshift.com/name: elad2111b
    controller-tools.k8s.io: "1.0"
  name: elad2111b-h262p
  namespace: uhc-development
  ownerReferences: []
  resourceVersion: "6708179"
  selfLink: /apis/hive.openshift.io/v1alpha1/namespaces/uhc-development/clusterdeployments/elad2111b-h262p
  uid: 70c015cf-ed8e-11e8-bceb-126966a81b5e
spec:
  clusterUUID: 392c0b29-7094-4fff-82ba-971b8b66dd42
  config:
    admin:
      email: etabak@redhat.com
      password:
        name: elad2111b-admin-c2mfj
      sshKey:
        name: elad2111b-ssh-xgbw4
    baseDomain: aws.openshift.com
    clusterID: elad2111b
    machines:
    - name: master
      platform:
        aws:
          iamRoleName: ""
          rootVolume:
            iops: 100
            size: 32
            type: gp2
          type: m5.large
      replicas: 1
    - name: worker
      platform:
        aws:
          iamRoleName: TBD
          rootVolume:
            iops: 100
            size: 32
            type: gp2
          type: m5.large
      replicas: 6
    networking:
      podCIDR: 10.2.0.0/16
      serviceCIDR: 10.3.0.0/16
      type: OpenshiftSDN
    platform:
      aws:
        defaultMachinePlatform:
          amiID: ami-097cceb29f8700328
          iamRoleName: ""
          rootVolume:
            iops: 0
            size: 0
            type: ""
          type: ""
        region: us-east-1
        vpcCIDRBlock: 10.0.0.0/16
        vpcID: ""
    pullSecret:
      name: elad2111b-pull-hznm8
  images:
    hiveImage: quay.io/twiest/hive-controller:20181119
    hiveImagePullPolicy: Always
    installerImage: quay.io/twiest/installer:20181119
    installerImagePullPolicy: Always
  platformSecrets:
    aws:
      credentials:
        name: elad2111b-aws-zv7f8
status:
  adminKubeconfigSecret:
    name: elad2111b-h262p-admin-kubeconfig
  apiURL: https://elad2111b-api.aws.openshift.com:6443
  installed: true
  webConsoleURL: https://elad2111b-api.aws.openshift.com:6443/console
`

**Comment by dgoodwin** [comment]
Ok no the master should not count as a worker and you should have had 6 workers. Looks like the cluster was torn down, but if you see this again please let me know so I can take a look. We'll need to go hunting in the cluster to check out the machinesets and machines in etcd there.

**Comment by tzvatot** [comment]
I see this again. Please let me know what info do you require for hunting it.

**Comment by dgoodwin** [comment]
oc get machinesets -o yaml --all-namespaces
Same for machines

Check the counts in AWS to see if one is there but broken.
