### ISSUE TITLE
[ipv6] hive-operator is in    CrashLoopBackOff  status

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#951]
git clone version:
https://github.com/openshift/hive.git
a5c260d3ff8dc9485669fe564b4393098ff0b593

[kni@provisionhost-0-0 ~]$ oc get pod
NAME                               READY   STATUS             RESTARTS   AGE
hive-controllers-58f5c8cd9-5shwf   1/1     Running            20         6h6m
hive-operator-686cd786b-v72gc      0/1     CrashLoopBackOff   68         6h8m
hiveadmission-59f9f568fc-7blmg     1/1     Running            0          6h7m
hiveadmission-59f9f568fc-kn659     1/1     Running            0          6h7m
qe-0-gxv7d-provision-pss4m         0/3     Pending            0          6h6m
[kni@provisionhost-0-0 ~]$ 

[kni@provisionhost-0-0 ~]$ oc logs hive-operator-686cd786b-v72gc
time="2020-04-21T13:30:34Z" level=info msg="Version: openshift/hive v1.0.1-27-ga5c260d3ff8dc9485669fe564b4393098ff0b593-dirty @ a5c260d3ff8dc9485669fe564b4393098ff0b593"
time="2020-04-21T13:30:35Z" level=fatal msg="Get https://[fd02::1]:443/api?timeout=32s: dial tcp [fd02::1]:443: connect: no route to host"

Network addresses from install-config.yaml:
  clusterNetwork:
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
  - fd02::/112

[kni@provisionhost-0-0 ~]$ oc describe pod hive-operator-686cd786b-v72gc
Name:         hive-operator-686cd786b-v72gc
Namespace:    hive
Priority:     0
Node:         worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com/fd2e:6f44:5dd8::146
Start Time:   Tue, 21 Apr 2020 06:57:47 +0000
Labels:       control-plane=hive-operator
              controller-tools.k8s.io=1.0
              pod-template-hash=686cd786b
Annotations:  k8s.ovn.org/pod-networks:
                {"default":{"ip_address":"fd01::4:808e:97ff:fe00:7c/64","mac_address":"82:8e:97:00:00:7c","gateway_ip":"fd01:0:0:4::1"}}
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "ovn-kubernetes",
                    "interface": "eth0",
                    "ips": [
                        "fd01::4:808e:97ff:fe00:7c"
                    ],
                    "mac": "82:8e:97:00:00:7c",
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Running
IP:           fd01::4:808e:97ff:fe00:7c
IPs:
  IP:           fd01::4:808e:97ff:fe00:7c
Controlled By:  ReplicaSet/hive-operator-686cd786b
Containers:
  hive-operator:
    Container ID:  cri-o://427770df80effa091b9fe42a9662b0073e584e985b14a87535b73f8f9c5503cb
    Image:         registry.ocp-edge-cluster-0.qe.lab.redhat.com:5000/openshift/hive-v4.0:hive
    Image ID:      registry.ocp-edge-cluster-0.qe.lab.redhat.com:5000/openshift/hive-v4.0@sha256:37d1c2d28e49dae8b91b05d4f60d6b7ac3f71ca925b7e2e0f8b41b572c2dca81
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/services/hive-operator
      --log-level
      info
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 21 Apr 2020 13:30:34 +0000
      Finished:     Tue, 21 Apr 2020 13:30:35 +0000
    Ready:          False
    Restart Count:  73
    Requests:
      cpu:      100m
      memory:   256Mi
    Liveness:   http-get http://:8080/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      CLI_CACHE_DIR:     /var/cache/kubectl
      HIVE_OPERATOR_NS:  hive (v1:metadata.namespace)
    Mounts:
      /var/cache/kubectl from kubectl-cache (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hive-operator-token-4jgtg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubectl-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hive-operator-token-4jgtg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hive-operator-token-4jgtg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                                                      Message
  ----     ------   ----                    ----                                                      -------
  Normal   Pulling  105m (x54 over 6h35m)   kubelet, worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com  Pulling image "registry.ocp-edge-cluster-0.qe.lab.redhat.com:5000/openshift/hive-v4.0:hive"
  Warning  BackOff  44s (x1495 over 6h28m)  kubelet, worker-0-1.ocp-edge-cluster-0.qe.lab.redhat.com  Back-off restarting failed container
[kni@provisionhost-0-0 ~]$ 

Workaround:
[kni@provisionhost-0-0 ~]$ oc delete pod hive-operator-686cd786b-v72gc
pod "hive-operator-686cd786b-v72gc" deleted
[kni@provisionhost-0-0 ~]$ oc get pod
NAME                               READY   STATUS    RESTARTS   AGE
hive-controllers-58f5c8cd9-5shwf   1/1     Running   22         6h35m
hive-operator-686cd786b-d6zsc      1/1     Running   0          19s
hiveadmission-59f9f568fc-7blmg     1/1     Running   0          6h35m
hiveadmission-59f9f568fc-kn659     1/1     Running   0          6h35m
qe-0-gxv7d-provision-pss4m         0/3     Pending   0          6h35m
[kni@provisionhost-0-0 ~]$

**Comment by staebler** [comment]
I suspect that this may be an issue with the health probes in an !Pv6-only cluster.

Can you please attach the logs from one of the hive-operator pods?

**Comment by staebler** [comment]
> I suspect that this may be an issue with the health probes in an !Pv6-only cluster.
> 
> Can you please attach the logs from one of the hive-operator pods?

Never mind about logs. I see it now.

**Comment by staebler** [comment]
It is failing because your pod cannot connect to the kube API server.
```
time="2020-04-21T13:30:35Z" level=fatal msg="Get https://[fd02::1]:443/api?timeout=32s: dial tcp [fd02::1]:443: connect: no route to host"
```

**Comment by gregsheremeta** [comment]
seems to be an environment issue. I know there was a recent successful ipv6 install. Please open a Jira if you need more assistance.

**Comment by achuzhoy** [comment]
@gregsheremeta  
note: the install was successful for me too. Moreover I was able to deploy a spoke cluster despite the multiple restarts. 
Was it verified that hive-operator doesn't restart on the setup you mentioned?
