### ISSUE TITLE
"skipGatherLogs": true seems to be disregarded.

### ISSUE THREAD

**Issue by achuzhoy** [openshift/hive#970]
Attempting to deploy a spoke cluster with hive on 4.5 (using the same automation used for 4.4).

[kni@provisionhost-0-0 hive]$ oc get pod -n hive
NAME                                       READY   STATUS             RESTARTS   AGE
cd-ocp-cluster-1-0-zzjjk-provision-dhjf7   0/3     Pending            0          149m
hive-controllers-565d4647dd-kt7hm          1/1     Running            9          149m
hive-operator-5976475d99-585hm             0/1     CrashLoopBackOff   25         150m
hiveadmission-586c8ccb86-6hjxc             1/1     Running            0          149m
hiveadmission-586c8ccb86-lr69f             1/1     Running            0          149m
[kni@provisionhost-0-0 hive]$

[kni@provisionhost-0-0 hive]$ oc describe pod cd-ocp-cluster-1-0-zzjjk-provision-dhjf7
Name:           cd-ocp-cluster-1-0-zzjjk-provision-dhjf7
Namespace:      hive
Priority:       0
Node:           <none>
Labels:         controller-uid=be302efa-f4c7-4be7-97c8-c6b177c4586d
                hive.openshift.io/cluster-deployment-name=cd-ocp-cluster-1
                hive.openshift.io/cluster-platform=baremetal
                hive.openshift.io/cluster-provision=cd-ocp-cluster-1-0-zzjjk
                hive.openshift.io/cluster-provision-name=cd-ocp-cluster-1-0-zzjjk
                hive.openshift.io/install=true
                hive.openshift.io/job-type=provision
                job-name=cd-ocp-cluster-1-0-zzjjk-provision
Annotations:    openshift.io/scc: restricted
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/cd-ocp-cluster-1-0-zzjjk-provision
Containers:
  installer:
    Image:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ef680d3965cb4bf8af83c8ea646c9aecb64b3037eea7d96779dc464365dbf9e6
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
    Args:
      cp -v /bin/openshift-install /output/openshift-install.tmp && mv -v /output/openshift-install.tmp /output/openshift-install && ls -la /output
    Environment:
      OPENSHIFT_INSTALL_INVOKER:                 hive
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE:  registry.svc.ci.openshift.org/ocp/release:4.5.0-0.nightly-2020-05-04-113741
      SSH_PRIV_KEY_PATH:                         /sshkeys/ssh-privatekey
      LIBVIRT_SSH_PRIV_KEY_PATH:                 /libvirtsshkeys/ssh-privatekey
    Mounts:
      /installconfig from installconfig (rw)
      /libvirtsshkeys from libvirtsshkeys (rw)
      /logs from logs (rw)
      /output from output (rw)
      /pullsecret from pullsecret (rw)
      /sshkeys from sshkeys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-installer-token-t2k5c (ro)
  cli:
    Image:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b49ab166ceef274fd453a2346d5830d9e5229981305bd6ade05291d354a132e7
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
    Args:
      cp -v /usr/bin/oc /output/oc.tmp && mv -v /output/oc.tmp /output/oc && ls -la /output
    Environment:
      OPENSHIFT_INSTALL_INVOKER:                 hive
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE:  registry.svc.ci.openshift.org/ocp/release:4.5.0-0.nightly-2020-05-04-113741
      SSH_PRIV_KEY_PATH:                         /sshkeys/ssh-privatekey
      LIBVIRT_SSH_PRIV_KEY_PATH:                 /libvirtsshkeys/ssh-privatekey
    Mounts:
      /installconfig from installconfig (rw)
      /libvirtsshkeys from libvirtsshkeys (rw)
      /logs from logs (rw)
      /output from output (rw)
      /pullsecret from pullsecret (rw)
      /sshkeys from sshkeys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-installer-token-t2k5c (ro)
  hive:
    Image:      registry.svc.ci.openshift.org/openshift/hive-v4.0:hive
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/hiveutil
    Args:
      install-manager
      --work-dir
      /output
      --log-level
      debug
      hive
      cd-ocp-cluster-1-0-zzjjk
    Environment:
      OPENSHIFT_INSTALL_INVOKER:                 hive
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE:  registry.svc.ci.openshift.org/ocp/release:4.5.0-0.nightly-2020-05-04-113741
      SSH_PRIV_KEY_PATH:                         /sshkeys/ssh-privatekey
      LIBVIRT_SSH_PRIV_KEY_PATH:                 /libvirtsshkeys/ssh-privatekey
    Mounts:
      /installconfig from installconfig (rw)
      /libvirtsshkeys from libvirtsshkeys (rw)
      /logs from logs (rw)
      /output from output (rw)
      /pullsecret from pullsecret (rw)
      /sshkeys from sshkeys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-installer-token-t2k5c (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  output:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  installconfig:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ocp-cluster-1-install-config
    Optional:    false
  pullsecret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cd-ocp-cluster-1-merged-pull-secret
    Optional:    false
  logs:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cd-ocp-cluster-1-install-logs
    ReadOnly:   false
  sshkeys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ocp-cluster-1-ssh-private-key
    Optional:    false
  libvirtsshkeys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ocp-cluster-1-ssh-private-key
    Optional:    false
  cluster-installer-token-t2k5c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cluster-installer-token-t2k5c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cd-ocp-cluster-1-0-zzjjk-provision-dhjf7": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "cd-ocp-cluster-1-0-zzjjk-provision-dhjf7": pod has unbound immediate PersistentVolumeClaims

[kni@provisionhost-0-0 hive]$ oc get hiveconfig hive -o json |jq ".spec.failedProvisionConfig"
{
  "skipGatherLogs": true
}

[kni@provisionhost-0-0 hive]$ oc get hiveconfig hive -o yaml
apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"hive.openshift.io/v1","kind":"HiveConfig","metadata":{"annotations":{},"name":"hive"},"spec":{"logLevel":"debug","targetNamespace":"hive"}}
  creationTimestamp: "2020-05-04T19:03:15Z"
  generation: 2
  name: hive
  resourceVersion: "36055"
  selfLink: /apis/hive.openshift.io/v1/hiveconfigs/hive
  uid: 0a30a324-454f-4e0d-ad86-97a6e2eda30e
spec:
  failedProvisionConfig:
    skipGatherLogs: true
  logLevel: debug
  targetNamespace: hive
status:
  aggregatorClientCAHash: 825ffafbcb1a9e13fa2d12a8e46b0e37
  configApplied: true
  observedGeneration: 2
[kni@provisionhost-0-0 hive]$ 

[kni@provisionhost-0-0 hive]$ oc get pvc
NAME                            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cd-ocp-cluster-1-install-logs   Pending                                                     150m
[kni@provisionhost-0-0 hive]$

**Comment by dgoodwin** [comment]
This was found to be insufficient time between editing hiveconfig and waiting for the pods to rollout.
