### ISSUE TITLE
delete-after annotation didn't work on us-east-2 (Ohio)

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#99]
We used the "delete-after" annotation with 8h settings.
It works fine for us-east-1 but not for us-east-2.
I had to manually delete EC2 instances running for days.
Didn't try other regions.

**Comment by dgoodwin** [comment]
What was the state of those cluster deployments in etcd?

Specifically was it still in etcd, did it have the deletionTimestamp set, and was an uninstall job run and what was it's status.

**Comment by dgoodwin** [comment]
Can you clarify the name of the cluster deployments involved if they still exist.
